### ISSUE TITLE
Stable Version 1.13.1 is broken on Android Studio 3 with Java 8  

### ISSUE THREAD

**Issue by gershnik-smartsheet** [AzureAD/azure-activedirectory-library-for-android#1015]
Create a project that depends on 1.13.1 with the following in Gradle config

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

and

buildTypes {
        release {
            minifyEnabled true //this enables native, rather than proguard minification
            useProguard false
            ...
}

The build then reliably fails with the following exception. Changing sourceCompatibility/targetCompatibility to Java 7 makes the problem disappear. I suspect something is wrong with your classes.jar signature that Java 8 doesn't like.

Caused by: java.lang.SecurityException: SHA-256 digest error for com/microsoft/aad/adal/AbstractMetadataRequestor.class
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:106)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:166)
	at com.android.build.gradle.shrinker.FullRunShrinker.processJarFile(FullRunShrinker.java:477)
	at com.android.build.gradle.shrinker.FullRunShrinker.buildGraph(FullRunShrinker.java:169)
	at com.android.build.gradle.shrinker.FullRunShrinker.run(FullRunShrinker.java:108)
	at com.android.build.gradle.internal.transforms.BuiltInShrinkerTransform.fullRun(BuiltInShrinkerTransform.java:160)
	at com.android.build.gradle.internal.transforms.BuiltInShrinkerTransform.transform(BuiltInShrinkerTransform.java:130)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:222)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:218)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:213)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 102 more

**Comment by iambmelt** [comment]
See #1030 for discussion of workaround until `aar` is updated
