### ISSUE TITLE
AuthenticationActivity causing WindowLeaked and application is getting crashed.

### ISSUE THREAD

**Issue by dcharya** [AzureAD/azure-activedirectory-library-for-android#1024]
Hi, 

I am using adal latest version library for Azure AD authentication integration in one of the application.

```java
com.microsoft.aad:adal:1.13.1 but still I am getting application crash.

android.view.WindowLeaked: Activity com.microsoft.aad.adal.AuthenticationActivity has leaked window android.widget.ZoomButtonsController$Container{21a02a99 V.E..... ......I. 0,0-1080,146} that was originally added here
                                                                 at android.view.ViewRootImpl.<init>(ViewRootImpl.java:382)
                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:261)
                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
                                                                 at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:370)
                                                                 at com.android.org.chromium.android_webview.AwZoomControls.invokeZoomPicker(AwZoomControls.java:29)
                                                                 at com.android.org.chromium.content.browser.ContentViewCore.onScrollBeginEventAck(ContentViewCore.java:1270)
                                                                 at com.android.org.chromium.content.browser.ContentViewCore.nativeOnTouchEvent(Native Method)
                                                                 at com.android.org.chromium.content.browser.ContentViewCore.onTouchEvent(ContentViewCore.java:1208)
                                                                 at com.android.org.chromium.android_webview.AwContents$AwViewMethodsImpl.onTouchEvent(AwContents.java:2312)
                                                                 at com.android.org.chromium.android_webview.AwContents.onTouchEvent(AwContents.java:1698)
                                                                 at com.android.webview.chromium.WebViewChromium.onTouchEvent(WebViewChromium.java:1910)
                                                                 at android.webkit.WebView.onTouchEvent(WebView.java:2286)
                                                                 at android.view.View.dispatchTouchEvent(View.java:8444)
                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
                                                                 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
                                                                 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2383)
                                                                 at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1724)
                                                                 at android.app.Activity.dispatchTouchEvent(Activity.java:2764)
                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2332)
                                                                 at android.view.View.dispatchPointerEvent(View.java:8655)
                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
                                                                 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4094)
                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3635)
                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3694)
                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3660)
                                                                 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3773)
                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3668)
                                                                 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3830)
                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3640)
                                                                 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3694)
                                                                 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3660)
                                                                 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3668)
                                                                 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3640)
                                                                 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5940)
                                                                 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5908)
                                                                 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5872)
                                                                 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6030)
                                                                 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:211)
                                                                 at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
                                                                 at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:197)
                                                             	at android.vi
```

**Comment by iambmelt** [comment]
@piqiums Did we ship a fix for this? In which version? If not, can you please prioritize and investigate?

**Comment by modislaszlox2** [comment]
Any update on this issue? I have the same problem.

**Comment by piqiums** [comment]
@iambmelt  There's an old similar issue which was closed before. https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/433  . It seems there's no code change for it before. I am looking into it.

**Comment by piqiums** [comment]
@dcharya thanks for reporting this issue, I am investigating and I need some information:
1. what's the device and what's the Android version?
2. what's the repro steps?
 Thanks

**Comment by iambmelt** [comment]
Closing due to inactivity
