### ISSUE TITLE
Crash when broker returns null for getIntentForInteractiveRequest

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#1031]
```java
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.putExtras(android.os.Bundle)' on a null object reference
          at com.microsoft.aad.adal.BrokerProxy.getIntentForBrokerActivity(BrokerProxy.java:596)
          at com.microsoft.aad.adal.AcquireTokenWithBrokerRequest.acquireTokenWithBrokerInteractively(AcquireTokenWithBrokerRequest.java:90)
          at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenInteractiveFlow(AcquireTokenRequest.java:532)
          at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:338)
          at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:46)
          at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:109)
          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
          at java.lang.Thread.run(Thread.java:761)
```

**Comment by addev-ashish** [comment]
Open questions to answers, why did this just start happening, what is the broker version and get some broker logs.
