### ISSUE TITLE
AuthenticationContext#acquireToken using null Activity & useDialog == false does not work

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1047]
See[ `AuthenticationContext#acquireToken(String, String, String, String, PromptBehavior, String,
String, AuthenticationCallback<AuthenticationResult>`](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L608-L650).

This implementation invokes [`AcquireTokenRequest#acquireToken(IWindowComponent, boolean, AuthenticationRequest, AuthenticationCallback<AuthenticationResult>)`](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java#L648) passing `null` and `false` as the first two parameters.

This causes [this check](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L513-L517) to fail, thus thowing an `AuthenticationException`.

The flow was broken in 848b290f6325f057af13b381c6bb6a69da85cbfc and merged in #655 -- it has been broken since June 2016.

**Comment by iambmelt** [comment]
There is a [single unit test](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/androidTest/java/com/microsoft/aad/adal/AcquireTokenRequestTest.java#L562-L605) which calls this `acquireToken()` implementation -- it validates that an `IllegalArgumentException` is thrown when claims are passed in both the `claims` and `extraQueryParameter` parameters

**Comment by iambmelt** [comment]
Tested the following changes:
```java
diff --git a/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java b/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java
index 9b9e4f77..1c5976d6 100644
--- a/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java
+++ b/adal/src/main/java/com/microsoft/aad/adal/AuthenticationContext.java
@@ -645,7 +645,7 @@ public class AuthenticationContext {
                     getRequestCorrelationId(), getExtendedLifetimeEnabled(), claims);
             request.setUserIdentifierType(UserIdentifierType.LoginHint);
             request.setTelemetryRequestId(requestId);
-            createAcquireTokenRequest(apiEvent).acquireToken(null, false, request, callback);
+            createAcquireTokenRequest(apiEvent).acquireToken(null, true, request, callback);
         }
     }
```

Yields
```java
11-27 14:52:09.756 5232-5247/com.microsoft.aad.adal.userappwithbroker D/OpenGLRenderer: endAllActiveAnimators on 0x89aa0500 (DropDownListView) with handle 0x8bcb9400
11-27 14:52:10.073 5232-5237/com.microsoft.aad.adal.userappwithbroker I/art: Do partial code cache collection, code=23KB, data=30KB
11-27 14:52:10.074 5232-5237/com.microsoft.aad.adal.userappwithbroker I/art: After code cache collection, code=23KB, data=30KB
11-27 14:52:10.074 5232-5237/com.microsoft.aad.adal.userappwithbroker I/art: Increasing code cache capacity to 128KB
11-27 14:52:11.269 5232-5247/com.microsoft.aad.adal.userappwithbroker D/OpenGLRenderer: endAllActiveAnimators on 0x89aa3d00 (DropDownListView) with handle 0x8bcb9480
11-27 14:52:12.411 5232-5232/com.microsoft.aad.adal.userappwithbroker V/PRNGFixes:applyOpenSSLFix: 2017-11-27 19:52:12-null-No need to apply the OpenSSL fix. ver:1.13.2
11-27 14:52:12.413 5232-5232/com.microsoft.aad.adal.userappwithbroker V/PRNGFixes:installLinuxPRNGSecureRandom: 2017-11-27 19:52:12-null-No need to apply the fix. ver:1.13.2
11-27 14:52:12.433 5232-5232/com.microsoft.aad.adal.userappwithbroker V/BrokerProxy: 2017-11-27 19:52:12-null-Device runs on 23 and above, skip the check for 22 and below. ver:1.13.2
11-27 14:52:12.443 5232-5232/com.microsoft.aad.adal.userappwithbroker V/AcquireTokenRequest:acquireToken: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Sending async task from thread:5232 ver:1.13.2
11-27 14:52:12.445 5232-6504/com.microsoft.aad.adal.userappwithbroker V/AcquireTokenRequest:acquireToken: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Running task in thread:6504 ver:1.13.2
11-27 14:52:12.448 5232-6504/com.microsoft.aad.adal.userappwithbroker V/AcquireTokenRequest:validateAuthority: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Start validating authority ver:1.13.2
11-27 14:52:12.455 5232-6504/com.microsoft.aad.adal.userappwithbroker V/Discovery: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Sending discovery request to query url.  ver:1.13.2 queryUrl: https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=https%3A%2F%2Flogin.microsoftonline.com%2F%252Fcommon%252Foauth2%252Fauthorize
11-27 14:52:12.458 5232-6504/com.microsoft.aad.adal.userappwithbroker V/WebRequestHandler: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-WebRequestHandler thread6504 ver:1.13.2
11-27 14:52:12.460 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:send: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-HttpWebRequest send.  ver:1.13.2  Thread: 6504
11-27 14:52:12.462 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-HttpWebRequest setupConnection. ver:1.13.2 Thread:6504
11-27 14:52:12.465 5232-6504/com.microsoft.aad.adal.userappwithbroker D/NetworkSecurityConfig: No Network Security Config specified, using platform default
11-27 14:52:12.467 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: x-client-Ver
11-27 14:52:12.469 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: return-client-request-id
11-27 14:52:12.471 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: Host
11-27 14:52:12.473 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: x-client-DM
11-27 14:52:12.475 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: x-client-OS
11-27 14:52:12.477 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: Accept
11-27 14:52:12.478 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: x-client-SKU
11-27 14:52:12.481 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:setupConnection: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Setting header.  ver:1.13.2 Header: client-request-id
11-27 14:52:12.647 5232-6504/com.microsoft.aad.adal.userappwithbroker V/HttpWebRequest:send: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Response is received. ver:1.13.2
11-27 14:52:12.652 5232-6504/com.microsoft.aad.adal.userappwithbroker V/AcquireTokenRequest:validateAuthority: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-The passed in authority is valid. ver:1.13.2
11-27 14:52:12.657 5232-6504/com.microsoft.aad.adal.userappwithbroker V/BrokerProxy:canSwitchToBroker: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Broker auth is turned off or no valid broker is available on the device, cannot switch to broker. ver:1.13.2
11-27 14:52:12.663 5232-6504/com.microsoft.aad.adal.userappwithbroker V/AuthenticationContext: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Put waiting request. requestId:89369359  CorrelationId: e724870a-e706-459d-8a9b-d7ec7983fc9a ver:1.13.2
11-27 14:52:12.666 5232-6504/com.microsoft.aad.adal.userappwithbroker V/BrokerProxy:canSwitchToBroker: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Broker auth is turned off or no valid broker is available on the device, cannot switch to broker. ver:1.13.2
11-27 14:52:12.667 5232-6504/com.microsoft.aad.adal.userappwithbroker V/AcquireTokenRequest:acquireTokenInteractiveFlow: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Starting Authentication Activity for embedded flow.  ver:1.13.2  Callback is: 89369359
11-27 14:52:12.671 5232-6504/com.microsoft.aad.adal.userappwithbroker V/AcquireTokenInteractiveRequest:acquireToken: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-FORCE_PROMPT is set for embedded flow, reset it as Always. ver:1.13.2
11-27 14:52:12.687 5232-6503/com.microsoft.aad.adal.userappwithbroker D/ApplicationLoaders: ignored Vulkan layer search path /data/app/com.android.chrome-1/lib/arm:/data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a for namespace 0xa968c090
11-27 14:52:12.693 5232-6503/com.microsoft.aad.adal.userappwithbroker I/WebViewFactory: Loading com.android.chrome version 62.0.3202.84 (code 320208402)
11-27 14:52:12.747 5232-6503/com.microsoft.aad.adal.userappwithbroker I/cr_LibraryLoader: Time to load native libraries: 5 ms (timestamps 1141-1146)
11-27 14:52:12.760 5232-6503/com.microsoft.aad.adal.userappwithbroker I/chromium: [INFO:library_loader_hooks.cc(46)] Chromium logging enabled: level = 0, default verbosity = 0
11-27 14:52:12.761 5232-6503/com.microsoft.aad.adal.userappwithbroker I/cr_LibraryLoader: Expected native library version number "62.0.3202.84", actual native library version number "62.0.3202.84"
11-27 14:52:12.793 5232-6503/com.microsoft.aad.adal.userappwithbroker I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.eb>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/RenderProcessGoneDetail;
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at com.android.webview.chromium.Ap com.android.webview.chromium.WebViewChromiumFactoryProvider.G(android.webkit.WebView, android.content.Context) (WebViewChromiumFactoryProvider.java:323)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View com.android.internal.policy.PhoneLayoutInflater.onCreateView(java.lang.String, android.util.AttributeSet) (PhoneLayoutInflater.java:58)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.onCreateView(android.view.View, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:717)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:785)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void com.microsoft.aad.adal.AuthenticationDialog$1.run() (AuthenticationDialog.java:86)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.Looper.loop() (Looper.java:154)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.HandlerThread.run() (HandlerThread.java:61)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.RenderProcessGoneDetail" on path: DexPathList[[zip file "/data/app/com.android.chrome-1/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-1/lib/arm, /data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at com.android.webview.chromium.Ap com.android.webview.chromium.WebViewChromiumFactoryProvider.G(android.webkit.WebView, android.content.Context) (WebViewChromiumFactoryProvider.java:323)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void com.android.webview.chromium.WebViewChromium.init(java.util.Map, boolean) (WebViewChromium.java:42)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int, java.util.Map, boolean) (WebView.java:636)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int, int) (WebView.java:572)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet, int) (WebView.java:555)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.webkit.WebView.<init>(android.content.Context, android.util.AttributeSet) (WebView.java:542)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance0!(java.lang.Object[]) (Constructor.java:-2)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at java.lang.Object java.lang.reflect.Constructor.newInstance(java.lang.Object[]) (Constructor.java:430)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.createView(java.lang.String, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:645)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View com.android.internal.policy.PhoneLayoutInflater.onCreateView(java.lang.String, android.util.AttributeSet) (PhoneLayoutInflater.java:58)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.onCreateView(android.view.View, java.lang.String, android.util.AttributeSet) (LayoutInflater.java:717)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:785)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.createViewFromTag(android.view.View, java.lang.String, android.content.Context, android.util.AttributeSet) (LayoutInflater.java:727)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.view.LayoutInflater.rInflate(org.xmlpull.v1.XmlPullParser, android.view.View, android.content.Context, android.util.AttributeSet, boolean) (LayoutInflater.java:858)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.view.LayoutInflater.rInflateChildren(org.xmlpull.v1.XmlPullParser, android.view.View, android.util.AttributeSet, boolean) (LayoutInflater.java:821)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.inflate(org.xmlpull.v1.XmlPullParser, android.view.ViewGroup, boolean) (LayoutInflater.java:518)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup, boolean) (LayoutInflater.java:426)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at android.view.View android.view.LayoutInflater.inflate(int, android.view.ViewGroup) (LayoutInflater.java:377)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void com.microsoft.aad.adal.AuthenticationDialog$1.run() (AuthenticationDialog.java:86)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
11-27 14:52:12.886 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.Looper.loop() (Looper.java:154)
11-27 14:52:12.887 5232-6503/com.microsoft.aad.adal.userappwithbroker I/art:     at void android.os.HandlerThread.run() (HandlerThread.java:61)
11-27 14:52:12.938 5232-6503/com.microsoft.aad.adal.userappwithbroker V/AuthenticationDialog:show: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-UserAgent:Mozilla/5.0 (Linux; Android 7.1.1; Nexus 6 Build/N6F27M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/62.0.3202.84 Mobile Safari/537.36 PKeyAuth/1.0 ver:1.13.2
11-27 14:52:12.945 5232-6503/com.microsoft.aad.adal.userappwithbroker I/AuthenticationDialog:show: 2017-11-27 19:52:12-e724870a-e706-459d-8a9b-d7ec7983fc9a-Showing authenticationDialog ver:1.13.2
11-27 14:52:12.965 5232-6503/com.microsoft.aad.adal.userappwithbroker E/AndroidRuntime: FATAL EXCEPTION: AcquireTokenRequestHandlerThread
                                                                                        Process: com.microsoft.aad.adal.userappwithbroker, PID: 5232
                                                                                        android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application
                                                                                            at android.view.ViewRootImpl.setView(ViewRootImpl.java:683)
                                                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
                                                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                                            at android.app.Dialog.show(Dialog.java:322)
                                                                                            at com.microsoft.aad.adal.AuthenticationDialog$1.run(AuthenticationDialog.java:171)
                                                                                            at android.os.Handler.handleCallback(Handler.java:751)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                                            at android.os.HandlerThread.run(HandlerThread.java:61)
```

Testing was performed both with `claims` parameter implementation and without: same results

**Comment by iambmelt** [comment]
From what I can tell, it's _possible_ that this implementation works when the supplied `mContext` is an instance of [`Service`](https://developer.android.com/reference/android/app/Service.html) **_and_** when `useDialog` is set to `true`. I don't have an easy way to test this at the moment: If this does work, it would require setting the following permission for API 23+ [(documentation)](https://developer.android.com/reference/android/Manifest.permission.html#SYSTEM_ALERT_WINDOW)
```xml
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
```

/cc @nazukj @shoatman @addev-ashish

**Comment by iambmelt** [comment]
Closing as no-op as library is crit-fixes only
