### ISSUE TITLE
wierd behaviour of ADAL on AcquireTokenSilent 

### ISSUE THREAD

**Issue by Eqbalazar** [AzureAD/azure-activedirectory-library-for-android#1075]
Exception on refresh silent Token
In background service on some phones that getting update to Android 7.1.1 , we are getting exception error on AcquireTokenSilent: 
**ADAL Library version using : com.microsoft.aad:adal:1.12.0**

Here is log : 
```
  12-12 10:48:43.566 9574-9651/? E/AndroidRuntime: FATAL EXCEPTION: pool-7-thread-1
                                                 Process: com.companyname.appname, PID: 9574
                                                     at com.microsoft.aad.adal.MemoryTokenCacheStore.getItem(Unknown Source)
                                                     at com.companyname.appname.a.h.getItem(Unknown Source)
                                                     at com.microsoft.aad.adal.TokenCacheAccessor.getRegularRefreshTokenCacheItem(Unknown Source)
                                                     at com.microsoft.aad.adal.TokenCacheAccessor.getATFromCache(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenRequest.access$200(Unknown Source)
                                                     at com.microsoft.aad.adal.AcquireTokenRequest$1.run(Unknown Source)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                     at java.lang.Thread.run(Thread.java:762)
```

**Comment by heidijinxujia** [comment]
@Eqbalazar Thank you for file this issue. 

This looks like a thread issue. Are you making calls from AuthenticationContext. acquireTokenSilent? It is a deprecated method. Please use com.microsoft.aad.adal.AuthenticationContext#acquireTokenSilentSync or com.microsoft.aad.adal.AuthenticationContext#acquireTokenSilentAsync instead, which are thread safe.

**Comment by Eqbalazar** [comment]
It is in Background Service : 

FileTokenCache _FileTokenCacheStore = new FileTokenCache(getApplicationContext(),
                            "fileCacheToken.dat");
                   AuthenticationContext m = new AuthenticationContext(getApplicationContext(), 
                                                                            Constants.AUTHORITY_URL, _FileTokenCacheStore);

**Comment by heidijinxujia** [comment]
Hi @Eqbalazar Just following up here, did the issue go resolved? Thanks.

**Comment by heidijinxujia** [comment]
Close the issue because we have not got the reply from customer for more than three weeks. Please feel free to reopen it if you got further question. Thanks.
