### ISSUE TITLE
CalledFromWrongThreadException When Handling PKEY Auth Errors (URI Validation)

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1079]
```
12-18 02:34:08.988  6051  6051 V BasicWebViewClient: 2017-12-18 02:34:08-ee6bb4fc-4547-4656-bf11-7672145c5d91-Navigation is detected:<omitted> ver:1.3.1
12-18 02:34:08.993  6051  6051 V BasicWebViewClient: 2017-12-18 02:34:08-ee6bb4fc-4547-4656-bf11-7672145c5d91-Webview detected request for client certificate ver:1.3.1
12-18 02:34:09.008  6051  6252 E BasicWebViewClient: DEVICE_CERTIFICATE_RESPONSE_FAILED:2017-12-18 02:34:09-ee6bb4fc-4547-4656-bf11-7672145c5d91-It is failed to create device certificate response ver:1.3.1 CertAuthorities
12-18 02:34:09.008  6051  6252 E BasicWebViewClient: com.microsoft.aad.adal.unity.AuthenticationException: CertAuthorities
12-18 02:34:09.008  6051  6252 E BasicWebViewClient:    at com.microsoft.aad.adal.unity.ChallangeResponseBuilder.validateChallangeRequest(ChallangeResponseBuilder.java:254)
12-18 02:34:09.008  6051  6252 E BasicWebViewClient:    at com.microsoft.aad.adal.unity.ChallangeResponseBuilder.getChallangeRequest(ChallangeResponseBuilder.java:266)
12-18 02:34:09.008  6051  6252 E BasicWebViewClient:    at com.microsoft.aad.adal.unity.ChallangeResponseBuilder.getChallangeResponseFromUri(ChallangeResponseBuilder.java:94)
12-18 02:34:09.008  6051  6252 E BasicWebViewClient:    at com.microsoft.aad.adal.unity.BasicWebViewClient$3.run(BasicWebViewClient.java:173)
12-18 02:34:09.008  6051  6252 E BasicWebViewClient:    at java.lang.Thread.run(Thread.java:818)
12-18 02:34:09.018  6051  6252 V AccountActivity: 2017-12-18 02:34:09-ee6bb4fc-4547-4656-bf11-7672145c5d91-Return To Caller:2005 ver:1.3.1
12-18 02:34:09.023  6051  6252 V AccountActivity: 2017-12-18 02:34:09-ee6bb4fc-4547-4656-bf11-7672145c5d91-displaySpinner:false ver:1.3.1
12-18 02:34:09.033  6051  6051 V BasicWebViewClient: 2017-12-18 02:34:09-ee6bb4fc-4547-4656-bf11-7672145c5d91-Page finished:urn:http-auth:PKeyAuth?SubmitUrl=https%3a%2f%2fsignon.bulletproof.net%3a443%2fadfs%2fls%2f%3flogin_hint%3djonathan.black%2540bulletproof.net%26wfresh%3d0%26wauth%3dhttp%253a%252f%252fschemas.microsoft.com%252fws%252f2008%252f06%252fidentity%252fauthenticationmethod%252fpassword%26client-request-id%3d255e6f0a-90f0-4c86-bf28-d47bc9cc8b02%26username%3djonathan.black%2540bulletproof.net%26wa%3dwsignin1.0%26wtrealm%3durn%253afederation%253aMicrosoftOnline%26wctx%3destsredirect%253d2%2526estsrequest%253drQIIAa1RMW_TQBjN2UkIEVIqxMCEOlCpQop9PiekjoREQxQnwWnaUmjsAel8tmMnts9xzm4bFiYWlogRNsYODEzAgsRG1SEDA-IndMrIiJH4CSzv6ZOe9N77XrkgCbIg3eMlQWreRQ0FIQhr1TqqS9UalGHVRMiqKpJNLAXLDRvX4pvljTJ9vrVevtK-bv948f3yNXcO2sEcJ8xtiiKhgRB4JKZz6jCBOo5HbIEmzKd0KjpkvANnKR1I-uBx3_DMSevkgLSdYUi35PYnAFYArAF4yYE33J0JDTFzcSiYPibTh2bi-zaLYkodIbTZigO_uMpwN3NFf4HG3sK-4go-HXvhW36sH0nU6h6ekAVNNXSaGshPtECKdLmfEqQElqokpuonxpP6xEQw1ZHCzGMl6Yc9BXcPIekO7mtnikvUaaIf76XmqDXH_7TGyJ1gtZMY6Ok5v-kyFs2z5jjyBJzVj3xPyEi0T0mWfmx_5IvZGdDwJw-WebDKg6v8jRLY4G-Dzdw2B8HvPHhfyN5aWdS-vfvc0j4YlVK-dCt3URBVRrqzvdmjRXLUE3FjFPbg1N3vaHIwG45apP1s5yzswgPUYfoD2JSWRXBRvLYbWjH1rHUx9-X6fxnmDw2&nonce=B78e0F4EX-zX5locUzObbQ&Version=1.0&Context=AAEAAA9PMTOQYKI1pChSquhxetLJbfwOcCCMyghOhOK0RpoX2Gdth-PxCjVO2escTM_q5__QD8lZgVS2QkvWw0ZhbRdGwAVoaM-E3HbkKSlyvV5cxWsCyB_HqFe8QVqntsXznRYwh-MW-OukK0alwRXv8nZ-SZ1fLTPczSg9uYIdGhuN5JHt-1dyQ3FsF-PcoPmUoMvfzNWSSzpF7CWQd6Iv45d9mRljdnclekdp18Ur5o2QhJ_HT6U2-CJ0l90IssUK2qv2sG38Ylr6uL5BRAELOeJ4LrfgxHf_so3suNysyBsW0uHf8FCVoZKicm7WTwa4tSQlAgJaHbLnBTEhxJJv7V6td6XzZ-dt44MOq4SOSz7SmsPtfkeZ47vWInJsNmkWigABAABG7PJdOF_V15o9Qd6e7pW8rMKkCbtaKx7_lT5SBNiPtD3qU1zHupELVxSWmkLQXaaHxHop_IoRwOpWGned1tEAjOYvO-R_-iwHpjQjlyqu4rrL-rWGu0e_ADJv4bmyD9RZNIaI3NGJ_R6vYOMw1rStjDxrIHRQ8F5Z8ysOB-pIZU7aEI0prj7lpUR8R79UdEPN4ToGkxQEKG5f3XjAqURflzAqUoq7SZbl14enqaST9VNTdU2ykbxGzBAJdoBQ78DV4BAcP2V1EIxX8p7KNySVVwH4_ui6fpTk3cCHGkeSUGrwdbAnU1MPCp6nhqoDFV6eI3VVodKNHLWIHLS4XlGwYAAAAHRdKHiB-IgkqrAc87cQQLJg0N4fi0IlLcEIDLyJ6WIiZSQK5fO-pXBEHjRRTIFVl2lA2NPdLhXrxCHTaJynxOQmDyosCEHYo5pLQEm1OFREE8wDl26QKKe4QbFX3QQpfA&CertAuthorities= ver:1.3.1
12-18 02:34:09.038  6051  6051 V AccountActivity: 2017-12-18 02:34:09-ee6bb4fc-4547-4656-bf11-7672145c5d91-displaySpinner:false ver:1.3.1
12-18 02:34:09.043  6051  6252 E AndroidRuntime: FATAL EXCEPTION: Thread-8186
12-18 02:34:09.043  6051  6252 E AndroidRuntime: Process: com.azure.authenticator:auth, PID: 6051
12-18 02:34:09.043  6051  6252 E AndroidRuntime: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8344)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1364)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5433)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.view.View.invalidateInternal(View.java:13997)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.view.View.invalidate(View.java:13961)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.view.View.setFlags(View.java:11885)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.view.View.setVisibility(View.java:8012)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at android.widget.ProgressBar.setVisibility(ProgressBar.java:1668)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at com.microsoft.aad.adal.unity.AccountActivity.displaySpinner(AccountActivity.java:589)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at com.microsoft.aad.adal.unity.AccountActivity.returnToCaller(AccountActivity.java:375)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at com.microsoft.aad.adal.unity.AccountActivity.access$1200(AccountActivity.java:82)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at com.microsoft.aad.adal.unity.AccountActivity$CustomWebViewClient.sendResponse(AccountActivity.java:505)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at com.microsoft.aad.adal.unity.BasicWebViewClient$3.run(BasicWebViewClient.java:221)
12-18 02:34:09.043  6051  6252 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
12-18 02:34:09.048  2782  3437 W ActivityManager:   Force finishing activity com.azure.authenticator/com.microsoft.aad.adal.unity.AccountActivity
```

**Comment by heidijinxujia** [comment]
This error happens when ADAL making a background auth call to Authenticator. I've made a PR for this fix in unity-fork. But I tried background silent call and could not get a repro for this issue with our adal sample app. Is there any detailed steps with rerpo?

**Comment by iambmelt** [comment]
@heidijinxujia Unfortunately, no. Issue was reported via customer escalation - as you can tell from the stacktrace, this is a confirmed issue against `unity` only.

There are [two methods](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/da9b0ddeab1cc92603d3b9058e8ab5fa7abc3614/adal/src/main/java/com/microsoft/aad/adal/AuthenticationActivity.java#L753-L779) inside of `AuthenticationActivitiy` that appear to be used similarly, but without a known-issue, I'd say we can close this for now and, if need be in the future, port the fix applied in `unity`
