### ISSUE TITLE
Android Telemetry does not report 5xx issues

### ISSUE THREAD

**Issue by nazukj** [AzureAD/azure-activedirectory-library-for-android#1090]
Android Telemetry does not report 5xx issues

@addev-ashish can add more details

**Comment by heidijinxujia** [comment]
I tried Fiddler with bpu and made a 502 response. It turns out it did not thrown SocketTimeoutException, it went through the processTokenResponse. And there is status code in the telemetry data. Here is the telemetry looks like.
```
11-02 18:20:13.098 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.is_frt:
11-02 18:20:13.098 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.correlation_id:f3d127b1-696f-4a56-ac17-efa97bafd664
11-02 18:20:13.098 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.is_rt:
11-02 18:20:13.098 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.device_id:7lUeJXtM9V0DD9UE1tWaA2sps2HSVQxiRn0CmNcPRNY=
11-02 18:20:13.098 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.application_name:com.microsoft.aad.adal.userappwithbroker
11-02 18:20:13.098 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.application_version:1.0
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.authority_type:aad
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.is_successful:false
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.authority_validation_status:yes
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.prompt_behavior:Auto
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.response_code:502
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.cache_event_count:4
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.api_id:115
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.ui_event_count:1
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.client_id:b92e0ba5-f86e-4411-8e18-6b5f928d968a
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.http_event_count:2
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.response_time:39132
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.request_id:27e39edf-b082-4719-b041-c41ed59ef95a
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.is_mrrt:
11-02 18:20:13.099 13303-13423/com.microsoft.aad.adal.userappwithbroker E/SampleTelemetry: Microsoft.ADAL.http_path:https://login.microsoftonline.com/oauth2/token/
11-02 18:20:13.101 13303-13422/com.microsoft.aad.adal.userappwithbroker E/AndroidRuntime: FATAL EXCEPTION: AcquireTokenRequestHandlerThread
                                                                                          Process: com.microsoft.aad.adal.userappwithbroker, PID: 13303
                                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Exception.getMessage()' on a null object reference
                                                                                              at com.microsoft.aad.adal.example.userappwithbroker.MainActivity$2.onError(MainActivity.java:283)
                                                                                              at com.microsoft.aad.adal.AcquireTokenRequest$CallbackHandler$1.run(AcquireTokenRequest.java:889)
                                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                              at android.os.Looper.loop(Looper.java:135)
                                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
```

p.s. the FATAL EXCEPTION is caused by the fiddler response which is a string instead of json. but it did not affect the test result here.

Confirmed from Ashish, quote here.

```
Most likely since Outlook samples at .2% we are losing the telemetry payloads that have 5xx errors. i ran your query for teams again and we have 5xx errors there.
```

**Comment by addev-ashish** [comment]
5xx is being reported, it might be sampling that is leaving it out of the data.
