### ISSUE TITLE
SecurityException is possible in BrokerAccountServiceHandler on LG devices

### ISSUE THREAD

**Issue by titorodi** [AzureAD/azure-activedirectory-library-for-android#1102]
Please ensure the following information is provided when logging a new issue:

<ul>
  <li>Expected behavior</li>
Don't Crash
  <li>Actual behavior</li>
ADAL Crashes on LG devices with the Broker installed on Profile A but the ADAL calling app (e.g. Teams) being in (Work) profile B
  <li>Steps to reproduce the problem</li>
Find an LG device
Install the Company Portal in user profile 1
Create a second user profile
Install Teams in the second user profile
Try to sign in to an AAD account to teams
  <li>Specifications like the version of the library, operating system etc</li>
  <li>Relevant logs and traces</li>

01-16 15:42:25.692  5121  6108 E AndroidRuntime: FATAL EXCEPTION: pool-16-thread-1
01-16 15:42:25.692  5121  6108 E AndroidRuntime: Process: com.microsoft.teams, PID: 5121
01-16 15:42:25.692  5121  6108 E AndroidRuntime: java.lang.SecurityException: Uid 1210266 is attempting to illegally masquerade as package com.microsoft.windowsintune.companyportal!
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1684)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at android.os.Parcel.readException(Parcel.java:1637)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at com.microsoft.aad.adal.IBrokerAccountService$Stub$Proxy.acquireTokenSilently(IBrokerAccountService.java:151)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at com.microsoft.aad.adal.BrokerAccountServiceHandler$2.onSuccess(BrokerAccountServiceHandler.java:131)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at com.microsoft.aad.adal.BrokerAccountServiceHandler$2.onSuccess(BrokerAccountServiceHandler.java:126)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at com.microsoft.aad.adal.BrokerAccountServiceHandler$5$1.run(BrokerAccountServiceHandler.java:326)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
01-16 15:42:25.692  5121  6108 E AndroidRuntime: at java.lang.Thread.run(Thread.java:761)

</ul>

<b>Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.</b>

For <b>privacy/security</b> issues please see instructions <a href="https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting">here</a>

**Comment by ravarora** [comment]
@iambmelt 
Got recent reports of a user facing this. 
Device LG  Premier Pro running Android 7.1.2
ADAL version used 1.16.3-hf2
