### ISSUE TITLE
ResourceNotFoundException: ADALError.getLocalizedDescription

### ISSUE THREAD

**Issue by caltseng** [AzureAD/azure-activedirectory-library-for-android#1162]
We are seeing some users run into a ResourceNotFound exception when trying to handle an error. 

I assume it's from the below method: 

```
    public String getLocalizedDescription(Context context) {
        // Optional overwrite to error descriptions from resource files.
        // Application can repeat the resource entries from libraries.
        // Application resource
        // merging operation will use the last one according to the import
        // order.
        if (context != null) {
            Configuration conf = context.getResources().getConfiguration();
            Resources resources = new Resources(context.getAssets(), context.getResources()
                    .getDisplayMetrics(), conf);
            return resources.getString(resources.getIdentifier(this.name(), "string",
                    context.getPackageName()));
        }
        return mDescription;
    }
```

```

java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2006, data=Intent {  launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 }(has extras) }} to activity {ols.microsoft.com.shiftr/ols.microsoft.com.shiftr.activity.LoginActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
	at android.app.ActivityThread.-wrap22(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6682)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
	at android.content.res.Resources.getText(Resources.java:1178)
	at android.content.res.Resources.getString(Resources.java:1224)
	at com.microsoft.aad.adal.ADALError.getLocalizedDescription(ADALError.java:626)
	at com.microsoft.aad.adal.AuthenticationException.getLocalizedMessage(AuthenticationException.java:220)
```

Below is the error that I assume isn't handled .
```

03-28 07:45:01.235   888   888 I Choreographer: Skipped 60 frames!  The application may be doing too much work on its main thread.
03-28 07:45:01.238   888   888 D InstrumentationHandler: Event: Eng_CustomEvent with Properties: {EventType=AdalAggregatedData, Microsoft.ADAL.correlation_id=4d6eea01-42ad-48ae-9f1f-70a2cf87c277, Microsoft.ADAL.device_id=aUhdx1Iob5UPEdjxrrU8AYG8Fnapt4tNj+/RRtxC1f8=, Microsoft.ADAL.application_name=ols.microsoft.com.shiftr, Microsoft.ADAL.application_version=1.53.0.2018032701, Microsoft.ADAL.authority_type=aad, Microsoft.ADAL.is_successful=false, EntityType=Event, Microsoft.ADAL.authority_validation_status=yes, Microsoft.ADAL.prompt_behavior=Always, Microsoft.ADAL.api_id=115, Microsoft.ADAL.client_id=60a9b775-4bf4-452d-9d77-b1f94d95d941, Microsoft.ADAL.response_time=152041, Microsoft.ADAL.request_id=b1a8b94a-177b-4f6c-9b0e-5e1179f9ac99, Microsoft.ADAL.api_error_code=BROKER_APP_INSTALLATION_STARTED}
03-28 07:45:01.239   888   888 W System.err: com.microsoft.aad.adal.AuthenticationException: Broker app installation started
03-28 07:45:01.239   888   888 W System.err: 	at com.microsoft.aad.adal.AcquireTokenRequest.onActivityResult(SourceFile:728)
03-28 07:45:01.239   888   888 W System.err: 	at com.microsoft.aad.adal.AuthenticationContext.onActivityResult(SourceFile:988)
03-28 07:45:01.239   888   888 W System.err: 	at com.microsoft.ols.o365auth.olsauth_android.O365Auth.onActivityResult(SourceFile:589)
03-28 07:45:01.239   888   888 W System.err: 	at ols.microsoft.com.shiftr.activity.b.onMAMActivityResult(SourceFile:438)
03-28 07:45:01.239   888   888 W System.err: 	at com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onActivityResult(SourceFile:346)
03-28 07:45:01.239   888   888 W System.err: 	at com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onActivityResult(SourceFile:324)
03-28 07:45:01.239   888   888 W System.err: 	at android.app.Activity.dispatchActivityResult(Activity.java:7256)
03-28 07:45:01.239   888   888 W System.err: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
03-28 07:45:01.239   888   888 W System.err: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
03-28 07:45:01.239   888   888 W System.err: 	at android.app.ActivityThread.-wrap22(ActivityThread.java)
03-28 07:45:01.239   888   888 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
03-28 07:45:01.239   888   888 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-28 07:45:01.239   888   888 W System.err: 	at android.os.Looper.loop(Looper.java:154)
03-28 07:45:01.239   888   888 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6682)
03-28 07:45:01.239   888   888 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
03-28 07:45:01.239   888   888 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
03-28 07:45:01.239   888   888 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
03-28 07:45:01.239   888   888 E com.microsoft.ols.o365auth.olsauth_android.O365Auth: Error during signin - Code: BROKER_APP_INSTALLATION_STARTED
03-28 07:45:01.239   888   888 D InstrumentationHandler: Event: AuthEvent_LogonAccessError with Properties: {EntityType=Event, ErrorReason=Broker app installation started}
03-28 07:45:01.241   888   888 W ResourceType: No package identifier when getting value for resource number 0x00000000
```

**Comment by caltseng** [comment]
Any movement on this? Another similar stack trace below

```
04-27 20:19:19.332 11633 11633 E AndroidRuntime: FATAL EXCEPTION: main
04-27 20:19:19.332 11633 11633 E AndroidRuntime: Process: ols.microsoft.com.shiftr, PID: 11633
04-27 20:19:19.332 11633 11633 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=2006, data=Intent { (has extras) }} to activity {ols.microsoft.com.shiftr/ols.microsoft.com.shiftr.activity.LoginActivity}: android.content.res.Resources$NotFoundException: String resource ID #0x0
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4118)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4161)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6142)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:804)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.content.res.Resources.getText(Resources.java:350)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:396)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.aad.adal.ADALError.getLocalizedDescription(SourceFile:626)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.aad.adal.AuthenticationException.getLocalizedMessage(SourceFile:220)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at ols.microsoft.com.shiftr.network.NetworkLayer.maybeHandleAuthError(SourceFile:3834)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at ols.microsoft.com.shiftr.network.NetworkLayer.access$300(SourceFile:224)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at ols.microsoft.com.shiftr.network.NetworkLayer$10.onFail(SourceFile:1121)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.ols.o365auth.olsauth_android.O365Auth$3.onError(SourceFile:709)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.waitingRequestOnError(SourceFile:863)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.waitingRequestOnError(SourceFile:845)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.onActivityResult(SourceFile:728)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.aad.adal.AuthenticationContext.onActivityResult(SourceFile:988)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.ols.o365auth.olsauth_android.O365Auth.onActivityResult(SourceFile:589)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at ols.microsoft.com.shiftr.activity.a.onMAMActivityResult(SourceFile:320)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.intune.mam.client.app.offline.OfflineActivityBehavior.onActivityResult(SourceFile:346)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at com.microsoft.intune.mam.client.support.v7.app.MAMAppCompatActivityBase.onActivityResult(SourceFile:324)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7015)
04-27 20:19:19.332 11633 11633 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4114)
```

**Comment by iambmelt** [comment]
Closing due to age; please reopen if this remains an issue
