### ISSUE TITLE
NPE in IBrokerAccountService.acquireTokenSilently

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#1164]
I have no repro, but crash report telemetry shows this became pretty frequent (from march 23). May be aligned with Company Portal release. Can you please take a look?
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase(java.util.Locale)' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1710)
       at android.os.Parcel.readException(Parcel.java:1654)
       at com.microsoft.aad.adal.IBrokerAccountService$Stub$Proxy.acquireTokenSilently(SourceFile:151)
       at com.microsoft.aad.adal.BrokerAccountServiceHandler$2.onSuccess(SourceFile:132)
       at com.microsoft.aad.adal.BrokerAccountServiceHandler$2.onSuccess(SourceFile:127)
       at com.microsoft.aad.adal.BrokerAccountServiceHandler$5$1.run(SourceFile:329)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)

**Comment by nazukj** [comment]
Issue is in the wrong repo :)
