### ISSUE TITLE
AutomationTestApp crashes when acquiring token with a fake authority.

### ISSUE THREAD

**Issue by v-dmkapi** [AzureAD/azure-activedirectory-library-for-android#1188]
Please ensure the following information is provided when logging a new issue:
class: AuthenticationContext
method: extractAuthority

<ul>
  <li>No crashing</li>
  <li>Crashing</li>
  <li>Run AutomationTestApp in android and attempt to acquire token with authority
"https://login.microsoftonline.com/"
</li>
  <li>adal for android</li>
  <li>E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.microsoft.aad.automation.testapp.adal, PID: 28654
                  java.lang.IllegalArgumentException: authority
                      at com.microsoft.aad.adal.AuthenticationContext.extractAuthority(AuthenticationContext.java:1198)
                      at com.microsoft.aad.adal.AuthenticationContext.initialize(AuthenticationContext.java:149)
                      at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:104)
                      at com.microsoft.aad.automation.testapp.SignInActivity.performAuthentication(SignInActivity.java:136)
                      at com.microsoft.aad.automation.testapp.SignInActivity.access$000(SignInActivity.java:62)
                      at com.microsoft.aad.automation.testapp.SignInActivity$1.onClick(SignInActivity.java:103)
                      at android.view.View.performClick(View.java:5609)
                      at android.view.View$PerformClick.run(View.java:22259)
                      at android.os.Handler.handleCallback(Handler.java:751)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
</li>
</ul>

<b>Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.</b>

For <b>privacy/security</b> issues please see instructions <a href="https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting">here</a>

**Comment by kreedula** [comment]
It's expected that authority url  has some characters beyond the host(third slash)
Valid : https://login.microsoftonline.com/common
Invalid : https://login.microsoftonline.com/
