### ISSUE TITLE
ClassNotFoundException: Didn't find class com.microsoft.aad.adal.R$layout

### ISSUE THREAD

**Issue by prachi2493** [AzureAD/azure-activedirectory-library-for-android#1195]
Adal Version used : 1.13.0
Facing this issue on some devices

Crash Trace:
05-17 09:39:22.162 21914 21914 V AuthenticationActivity: 2018-05-17 07:39:22-487d2c88-3ab0-42d7-963a-89f512a42d4a-displaySpinner:true showing:true ver:1.13.3
05-17 09:39:22.196 21914 21914 I BasicWebViewClient: 2018-05-17 07:39:22-487d2c88-3ab0-42d7-963a-89f512a42d4a-onReceivedHttpAuthRequest for host:post-adfs.post.at ver:1.13.3 
05-17 09:39:22.200 21914 21914 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/microsoft/aad/adal/R$layout;
05-17 09:39:22.200 21914 21914 W System.err: at com.microsoft.aad.adal.HttpAuthDialog.createDialog(HttpAuthDialog.java:86)
05-17 09:39:22.200 21914 21914 W System.err: at com.microsoft.aad.adal.HttpAuthDialog.<init>(HttpAuthDialog.java:67)
05-17 09:39:22.201 21914 21914 W System.err: at com.microsoft.aad.adal.BasicWebViewClient.onReceivedHttpAuthRequest(BasicWebViewClient.java:86)
05-17 09:39:22.201 21914 21914 W System.err: at com.android.webview.chromium.Ap.onReceivedHttpAuthRequest(WebViewContentsClientAdapter.java:444)
05-17 09:39:22.201 21914 21914 W System.err: at org.chromium.android_webview.AwContents.onReceivedHttpAuthRequest(AwContents.java:722)
05-17 09:39:22.201 21914 21914 W System.err: at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
05-17 09:39:22.201 21914 21914 W System.err: at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:9)
05-17 09:39:22.201 21914 21914 W System.err: at android.os.Handler.dispatchMessage(Handler.java:102)
05-17 09:39:22.201 21914 21914 W System.err: at android.os.Looper.loop(Looper.java:154)
05-17 09:39:22.201 21914 21914 W System.err: at android.app.ActivityThread.main(ActivityThread.java:6816)
05-17 09:39:22.201 21914 21914 W System.err: at java.lang.reflect.Method.invoke(Native Method)
05-17 09:39:22.201 21914 21914 W System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
05-17 09:39:22.201 21914 21914 W System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)
05-17 09:39:22.202 21914 21914 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.microsoft.aad.adal.R$layout" on path: DexPathList[[zip file "/data/app/com.fiberlink.maas360.android.docs-1/base.apk"],nativeLibraryDirectories=[/data/app/com.fiberlink.maas360.android.docs-1/lib/arm, /data/app/com.fiberlink.maas360.android.docs-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
05-17 09:39:22.202 21914 21914 W System.err: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
05-17 09:39:22.202 21914 21914 W System.err: at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
05-17 09:39:22.202 21914 21914 W System.err: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
05-17 09:39:22.202 21914 21914 W System.err: ... 13 more

**Comment by ankit-ankuagrawal** [comment]
Any update on this.

**Comment by kreedula** [comment]
I am not able to reproduce the issue. Can you give us more information about the specific device and OS version where this issue is seen? Also steps to reproduce will be helpful.

Per logs, it seems to throw a NoClassDefFoundError exception when trying to inflate the layout of the authentication dialog. I have verified that the layout file http_auth_dialog.xml is present in the aar.

**Comment by prachi2493** [comment]
This issue is not device or OS specific and we are using Option 5: jar package inside libs folder on our end.
Saw this same issue occurring before:
https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/361 
and fix was provided.Could you look into it

**Comment by ankit-ankuagrawal** [comment]
@kreedula any update here.

**Comment by kreedula** [comment]
@ankit-ankuagrawal @prachi2493 We have identified issue, fix will be added soon

**Comment by ankit-ankuagrawal** [comment]
@kreedula 
Thank you for the update.
Can you please let us know, in which release this fix will be coming and what will be the timeline.

For our Customer they are not able to logging at all, because App is getting crashed whenever trying to logging.

Can you please suggest some work around for mean time, so that until the release  we can suggest or do some work, so that customer can sign in successful.

This is holding deal with the customer.

**Comment by kreedula** [comment]
@ankit-ankuagrawal 
We don't have an exact timeline yet, but we expect it to be in next release.

For a work around, I assume you are using `private IWindowComponent wrapFragment(final Fragment fragment)`  and passing the fragment to `acquireToken`. Instead you can try implementing your authentication logic in an Activity and pass that to the `acquireToken` call

**Comment by prachi2493** [comment]
We are already implementing our authentication logic in activity and passing the same to acquireToken call.
If you could suggest some other possible workaround it would be helpful

**Comment by iambmelt** [comment]
Closing due to inactivity and age; please reopen if this remains an issue
