### ISSUE TITLE
NullPointerException in  isMultipleMRRTsMatchingGivenApp

### ISSUE THREAD

**Issue by msyulw** [AzureAD/azure-activedirectory-library-for-android#1278]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
	at com.microsoft.aad.adal.TokenCacheAccessor.isMultipleMRRTsMatchingGivenApp(TokenCacheAccessor.java:327)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryMRRT(AcquireTokenSilentHandler.java:261)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryRT(AcquireTokenSilentHandler.java:196)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(AcquireTokenSilentHandler.java:107)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(AcquireTokenRequest.java:438)
	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(AcquireTokenRequest.java:401)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:354)
	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:333)
	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:47)
	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by sindhu181994** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
       at com.microsoft.aad.adal.TokenCacheAccessor.isMultipleMRRTsMatchingGivenApp(SourceFile:440)
       at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryMRRT(SourceFile:268)
       at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryRT(SourceFile:216)
       at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(SourceFile:114)
       at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(SourceFile:499)
       at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(SourceFile:475)
       at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(SourceFile:379)
       at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(SourceFile:358)
       at com.microsoft.aad.adal.AcquireTokenRequest.access$200(SourceFile:57)
       at com.microsoft.aad.adal.AcquireTokenRequest$1.run(SourceFile:131)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by sindhu181994** [comment]
After enabling proguard, we are facing this issue while updating the app.

**Comment by suhailali** [comment]
@sindhu181994 I am also facing the same issue. Most of the time after app update users are facing this issue. The app is crashing. My logs are proguarded.
com.microsoft.aad.adal.t0.a SourceFile:83
com.microsoft.aad.adal.e.c SourceFile:15
com.microsoft.aad.adal.e.d SourceFile:15
com.microsoft.aad.adal.e.a SourceFile:9
com.microsoft.aad.adal.d.e SourceFile:3
com.microsoft.aad.adal.d.a SourceFile:63
com.microsoft.aad.adal.d.d SourceFile:3
com.microsoft.aad.adal.d.b SourceFile:2
com.microsoft.aad.adal.d.a SourceFile:3
com.microsoft.aad.adal.d$a.run SourceFile:4
java.util.concurrent.ThreadPoolExecutor.runWorker ThreadPoolExecutor.java:1167
java.util.concurrent.ThreadPoolExecutor$Worker.run ThreadPoolExecutor.java:641
java.lang.Thread.run Thread.java:919

@iambmelt, Will there be any fix happening on this? If not what can be done from our codebase to resolve or catch this, so that the app won't crash. I have already tried wrapping with a try-catch, but the error is not propagating back to my code.

**Comment by suhailali** [comment]
@msyulw @sindhu181994, Did you fix the issue. If yes please post the fix.

**Comment by iambmelt** [comment]
@suhailali [ADAL does not currently support use with ProGuard](https://github.com/AzureAD/azure-activedirectory-library-for-android#proguard)

**Comment by sindhu181994** [comment]
@iambmelt  Already disabled obfuscation of ADAL, but still it is happening after app update

**Comment by ali-suhail** [comment]
@sindhu181994 Yes, you are right.

@iambmelt Please have a look at this PR https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/1550 by zeee4real.

**Comment by iambmelt** [comment]
Removing assignee as they're no longer contributing to this project
