### ISSUE TITLE
[1.15.1] Crash when creating cache keys for FOCI tokens

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#1329]
```java
09-27 18:41:34.353 28012 29550 E AndroidRuntime: FATAL EXCEPTION: pool-111-thread-1
09-27 18:41:34.353 28012 29550 E AndroidRuntime: Process: <omitted>, PID: 28012
09-27 18:41:34.353 28012 29550 E AndroidRuntime: java.lang.IllegalArgumentException: both clientId and familyClientId are null
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.CacheKey.createCacheKey(SourceFile:93)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.CacheKey.createCacheKeyForFRT(SourceFile:198)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor$1.makeKey(SourceFile:514)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor.addDeletionKeyForMRRTOrFRTEntry(SourceFile:602)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor.addDeletionKeysForMRRTOrFRTEntry(SourceFile:592)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor.getKeyListToRemoveForMRRTOrFRT(SourceFile:523)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.TokenCacheAccessor.removeTokenCacheItem(SourceFile:395)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.removeTokensForUser(SourceFile:508)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentWithBroker(SourceFile:475)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(SourceFile:442)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(SourceFile:367)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(SourceFile:346)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(SourceFile:53)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(SourceFile:123)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-27 18:41:34.353 28012 29550 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by demoritas** [comment]
we did run into this today with 1.15

--- working in proguard --- 
-keepnames class com.microsoft.aad.adal.*

--- breaking in proguard --- 
-keep class com.microsoft.aad.adal.** {
  *;
}

**Comment by ravarora** [comment]
We are facing the same issue with ADAL 1.16.0 on devices running Android 8.0.0 and 8.1.0
Stacktrace:
java.lang.IllegalArgumentException: both clientId and familyClientId are null
	at com.microsoft.aad.adal.CacheKey.createCacheKey(CacheKey.java:93)
	at com.microsoft.aad.adal.CacheKey.createCacheKeyForFRT(CacheKey.java:198)
	at com.microsoft.aad.adal.TokenCacheAccessor$1.makeKey(TokenCacheAccessor.java:522)
	at com.microsoft.aad.adal.TokenCacheAccessor.addDeletionKeyForMRRTOrFRTEntry(TokenCacheAccessor.java:610)
	at com.microsoft.aad.adal.TokenCacheAccessor.addDeletionKeysForMRRTOrFRTEntry(TokenCacheAccessor.java:600)
	at com.microsoft.aad.adal.TokenCacheAccessor.getKeyListToRemoveForMRRTOrFRT(TokenCacheAccessor.java:531)
	at com.microsoft.aad.adal.TokenCacheAccessor.removeTokenCacheItem(TokenCacheAccessor.java:403)
	at com.microsoft.aad.adal.AcquireTokenRequest.removeTokensForUser(AcquireTokenRequest.java:542)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentWithBroker(AcquireTokenRequest.java:509)
	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(AcquireTokenRequest.java:476)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:373)
	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:352)
	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:55)
	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

**Comment by demoritas** [comment]
Is there any update on this? This issue prevents us from moving to the latest adal version

**Comment by ravarora** [comment]
Hello Team. Is there any update on this?

**Comment by demoritas** [comment]
still happening for us with 1.16
