### ISSUE TITLE
 W/KeyStore: KeyStore exception     android.os.ServiceSpecificException:  (code 7)

### ISSUE THREAD

**Issue by Ktirumalsetty** [AzureAD/azure-activedirectory-library-for-android#1368]
Getting below error in Android P emulator Pixel 2 API 28 at below line 

using below version 

implementation 'com.microsoft.aad:adal:1.2.2'

mAuthContext = new AuthenticationContext(this,
                    Constants.AUTHORITY_URL, false);

W/KeyStore: KeyStore exception
    android.os.ServiceSpecificException:  (code 7)
        at android.os.Parcel.createException(Parcel.java:1956)
        at android.os.Parcel.readException(Parcel.java:1910)
        at android.os.Parcel.readException(Parcel.java:1860)
        at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
        at android.security.KeyStore.get(KeyStore.java:195)
        at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:539)
        at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:426)
        at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:168)
        at com.microsoft.aad.adal.DefaultTokenCacheStore.<init>(DefaultTokenCacheStore.java:103)
        at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:152)

**Comment by iambmelt** [comment]
Hi @Ktirumalsetty 

Are you able to get a trace of this exception from a [newer version of the library](https://search.maven.org/search?q=g:com.microsoft.aad%20AND%20a:adal&core=gav)? `1.2.2` is rather old and was released in August of 2016.

My suspicion is that this error may coming from the Android system due to Android P changes (See section ['Compatibility through public APIs'](https://android-developers.googleblog.com/2018/05/whats-new-in-android-p-beta.html)) - specifically, it may related to our use of [`KeyStore#getEntry`](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/blob/dev/common/src/main/java/com/microsoft/identity/common/adal/internal/cache/StorageHelper.java#L418-L419) per [this post](https://stackoverflow.com/questions/52024752/android-p-keystore-exception-android-os-servicespecificexception/52295484#52295484) on StackOverflow.

**Comment by Ktirumalsetty** [comment]
HI @iambmelt Thanks for the reply no issue with the latest version 'com.microsoft.aad:adal:1.16.0'
