### ISSUE TITLE
Mocking in tests after upgrading to androidx fails due to SHA-256 digest error

### ISSUE THREAD

**Issue by Sammekl** [AzureAD/azure-activedirectory-library-for-android#1373]
After I upgraded to Android Studio 3.3 and androidx, I am no longer able to mock classes which use some part of adal. The app itself runs fine without any issues, unit testing gives issues

I tried to mock an interface like this:
```
interface View {
    fun authenticate(authenticationCallback: AuthenticationCallback<AuthenticationResult>)
}
```

When I run the test, the following exception is thrown:
```
Caused by: java.lang.SecurityException: SHA-256 digest error for com/microsoft/aad/adal/AuthenticationCallback.class
	at sun.security.util.ManifestEntryVerifier.verify(ManifestEntryVerifier.java:218)
	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:241)
	at java.util.jar.JarVerifier.update(JarVerifier.java:228)
	at java.util.jar.JarVerifier$VerifierStream.read(JarVerifier.java:482)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at net.bytebuddy.description.method.MethodList$ForLoadedMethods.<init>(MethodList.java:94)
	at net.bytebuddy.description.type.TypeDescription$ForLoadedType.getDeclaredMethods(TypeDescription.java:8411)
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Factory$Default$1.represent(InstrumentedType.java:349)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:716)
	at net.bytebuddy.ByteBuddy.redefine(ByteBuddy.java:691)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.transform(InlineBytecodeGenerator.java:211)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at sun.instrument.InstrumentationImpl.retransformClasses0(Native Method)
	at sun.instrument.InstrumentationImpl.retransformClasses(InstrumentationImpl.java:144)
	at org.mockito.internal.creation.bytebuddy.InlineBytecodeGenerator.triggerRetransformation(InlineBytecodeGenerator.java:161)
```

I've tried upgrading mockito-kotlin and dexmaker, but this didn't help.

**Comment by Sammekl** [comment]
I resolved this issue by using Jitpack to retrieve the ADAL dependency. See this comment for more information: https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/1030#issuecomment-342611385
