### ISSUE TITLE
ClientInfo as a property in AuthenticationResult should be serializable

### ISSUE THREAD

**Issue by liwa** [AzureAD/azure-activedirectory-library-for-android#1376]
Please ensure the following information is provided when logging a new issue:

* Expected behavior
 ClientInfo should be serializable and serialize AuthenticationResult should not crash
* Actual behavior
Serializing AuthenticationResult cause crash.
* Steps to reproduce the problem

                                                                            *Stack* : 
                                                                            ======= 
                                                                            java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.microsoft.aad.adal.AuthenticationResult)
                                                                                at android.os.Parcel.writeSerializable(Parcel.java:1468)
                                                                                at com.microsoft.authorization.signin.OdbSignInContext.writeToParcel(OdbSignInContext.java:185)
                                                                                at android.os.Parcel.writeParcelable(Parcel.java:1437)
                                                                                at android.os.Parcel.writeValue(Parcel.java:1343)
                                                                                at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
                                                                                at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                                                at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                                                at android.os.Parcel.writeBundle(Parcel.java:711)
                                                                                at android.app.FragmentState.writeToParcel(Fragment.java:141)
                                                                                at android.os.Parcel.writeTypedArray(Parcel.java:1254)
                                                                                at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:380)
                                                                                at android.os.Parcel.writeParcelable(Parcel.java:1437)
                                                                                at android.os.Parcel.writeValue(Parcel.java:1343)
                                                                                at android.os.Parcel.writeArrayMapInternal(Parcel.java:686)
                                                                                at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330)
                                                                                at android.os.Bundle.writeToParcel(Bundle.java:1079)
                                                                                at android.os.Parcel.writeBundle(Parcel.java:711)
                                                                                at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3153)
                                                                                at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3417)
                                                                                at android.os.Handler.handleCallback(Handler.java:739)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:148)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                             Caused by: java.io.NotSerializableException: com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.ClientInfo
                                                                                at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1344)
                                                                                at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                                at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                                at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                                at java.io.ObjectOutputStream.writeFieldValues(ObjectOutputStream.java:959)
                                                                                at java.io.ObjectOutputStream.defaultWriteObject(ObjectOutputStream.java:360)
                                                                                at java.io.ObjectOutputStream.writeHierarchy(ObjectOutputStream.java:1054)
                                                                                at java.io.ObjectOutputStream.writeNewObject(ObjectOutputStream.java:1384)
                                                                                at java.io.ObjectOutputStream.writeObjectInternal(ObjectOutputStream.java:1651)
                                                                                at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1497)
                                                                                at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:1461)
                                                                                at android.os.Parcel.writeSerializable(Parcel.java:1463)
                                                                                at com.microsoft.authorization.signin.OdbSignInContext.writeToParcel(OdbSignInContext.java:185) 
                                                                                at android.os.Parcel.writeParcelable(Parcel.java:1437) 
                                                                                at android.os.Parcel.writeValue(Parcel.java:1343) 
                                                                                at android.os.Parcel.writeArrayMapInternal(Parcel.java:686) 
                                                                                at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1330) 
                                                                                at android.os.Bundle.writeToParcel(Bundle.java:1079) 
* Specifications like the version of the library, operating system etc.
1.16
* Relevant logs and traces

**Please note: Do not include sensitive information like PII, OII, credentials, secrets, and tokens.**

For **privacy/security** issues please see instructions [here](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/README.md#security-reporting)

**Comment by kreedula** [comment]
This is addressed, but has not yet been release.

**Comment by iambmelt** [comment]
Related: #380
