### ISSUE TITLE
NullPointerException in AzureActiveDirectoryOAuth2Strategy.getIssuerCacheIdentifier()

### ISSUE THREAD

**Issue by daniel-robertson** [AzureAD/azure-activedirectory-library-for-android#1390]
A change introduced in ADAL 1.15.0 is resulting in crashes during login. The issue is still present in the latest version of ADAL (1.16.1).

I can reproduce this consistently, but it requires that both Company Portal and Authenticator are not installed on the device. The exception is thrown shortly after `ADALAuthenticationContext.onActivityResult()` is called from the activity.

It's unclear whether ADAL should be able to handle exceptions when calling `ADALOAuth2TokenCache.save()` or if this is a bug in the common library; if this should be handled by the common library I will re-file this issue under the appropriate repo.

``` 
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectoryCloud.isValidated()' on a null object reference
        at com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectoryOAuth2Strategy.getIssuerCacheIdentifier(AzureActiveDirectoryOAuth2Strategy.java:109)
        at com.microsoft.identity.common.internal.cache.ADALOAuth2TokenCache.save(ADALOAuth2TokenCache.java:129)
        at com.microsoft.aad.adal.TokenCacheAccessor.updateTokenCacheUsingCommonCache(TokenCacheAccessor.java:359)
        at com.microsoft.aad.adal.TokenCacheAccessor.updateTokenCache(TokenCacheAccessor.java:315)
        at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:126)
        at com.microsoft.aad.adal.AcquireTokenRequest$3.run(AcquireTokenRequest.java:885)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by vicalcazar** [comment]
This issue still occurs on version 1.16.3 of the library.  Any there are any updates on this issue?

**Comment by iambmelt** [comment]
@daniel-robertson @vicalcazar Can you provide any additional information about the repro you have on this crash? Whether it's device/OS version specific? Steps to repro, etc?

**Comment by vicalcazar** [comment]
This is occurring in our staging environment and is not specific to device/OS version. Following up offline with repro steps and test branch.  Thanks @iambmelt.
