### ISSUE TITLE
ADAL Plugin integration is crashing with proguard/dexguard

### ISSUE THREAD

**Issue by rupeshgaud11** [AzureAD/azure-activedirectory-library-for-android#1487]
Expected Behavior : The release apk with dexguard or proguard should launch AuthenticationActivity without any crash.(applied proguard rules as per github documentation)

Actual Behavior: App is crashing with below exception
java.lang.RuntimeException: Unable to start activity ComponentInfo{**/com.microsoft.aad.adal.AuthenticationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.webkit.WebSettings android.webkit.WebView.getSettings()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2728)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2814)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6290)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
		
Steps to reproduce:
1. Apply proguard as per github documentation : https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/ProGuard
2. Run release build and install the apk.
3. App will crash on launching the AuthenticationActivity.

Environment : Android Target SDK version 29 
Devices: Tested on multiple devices
Gradle : distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
ADAL Dependency: 
implementation('com.microsoft.aad:adal:1.16.3') {
        // if your app includes android support
        // libraries or Gson in its dependencies
        // exclude that groupId from ADAL's compile
        // task by un-commenting the appropriate
        // line below

        exclude group: 'com.android.support'
        exclude group: 'com.google.code.gson'
    }

**Comment by kreedula** [comment]
Hi @rupeshgaud11 : 
The issue seem to be `android webkit` not ADAL itself.
I will try to use a test app with proguard and see if it's reproducible.

To confirm you are only seeing this issue only if proguard obfuscation is enabled  ?

**Comment by iambmelt** [comment]
Closing due to inactivity
