### ISSUE TITLE
Gradle Build failing suddenly from VSO

### ISSUE THREAD

**Issue by v-vedas** [AzureAD/azure-activedirectory-library-for-android#1554]
Android Gradle build failing from VSO suddenly with below error. without any code or configuration changes

Error: The process 'D:\a\1\s\android\gradlew.bat' failed with exit code 1
    at ExecState._setResult (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.173.0\node_modules\azure-pipelines-task-lib\toolrunner.js:816:25)
    at ExecState.CheckComplete (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.173.0\node_modules\azure-pipelines-task-lib\toolrunner.js:799:18)
    at ChildProcess.<anonymous> (D:\a\_tasks\Gradle_8d8eebd8-2b94-4c97-85af-839254cc6da4\2.173.0\node_modules\azure-pipelines-task-lib\toolrunner.js:721:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
##[error]Error: The process 'D:\a\1\s\android\gradlew.bat' failed with exit code 1

**Comment by iambmelt** [comment]
@v-vedas These error messages are not from MSAL. Nothing here to troubleshoot
