### ISSUE TITLE
[ADAL 1.15.1] Return DEVELOPER_AUTHORITY_IS_NOT_VALID_INSTANCE on android 4.0.3 when using proxy wifi

### ISSUE THREAD

**Issue by Phanqui2020** [AzureAD/azure-activedirectory-library-for-android#1594]
com.microsoft.aad.adal.AuthenticationException: Socket is closed
        at com.microsoft.aad.adal.Discovery.performInstanceDiscovery(Discovery.java:262)
        at com.microsoft.aad.adal.Discovery.validateAuthority(Discovery.java:141)
        at com.microsoft.aad.adal.AcquireTokenRequest.validateAuthority(AcquireTokenRequest.java:306)
        at com.microsoft.aad.adal.AcquireTokenRequest.performAuthorityValidation(AcquireTokenRequest.java:216)
        at com.microsoft.aad.adal.AcquireTokenRequest.validateAcquireTokenRequest(AcquireTokenRequest.java:184)
        at com.microsoft.aad.adal.AcquireTokenRequest.access$100(AcquireTokenRequest.java:53)
        at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:122)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
        at java.lang.Thread.run(Thread.java:856)

     Caused by: java.net.SocketException: Socket is closed
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:262)
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:273)
        at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:257)
        at libcore.net.http.HttpConnection.setupSecureSocket(HttpConnection.java:210)
        at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.makeSslConnection(HttpsURLConnectionImpl.java:477)
        at libcore.net.http.HttpsURLConnectionImpl$HttpsEngine.connect(HttpsURLConnectionImpl.java:441)
        at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
        at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:273)
        at libcore.net.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:168)
        at libcore.net.http.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:270)
        at com.microsoft.identity.common.adal.internal.net.HttpWebRequest.send(HttpWebRequest.java:144)
        at com.microsoft.identity.common.adal.internal.net.WebRequestHandler.sendGet(WebRequestHandler.java:62)
        at com.microsoft.aad.adal.Discovery.sendRequest(Discovery.java:286)
        at com.microsoft.aad.adal.Discovery.performInstanceDiscovery(Discovery.java:244)
        at com.microsoft.aad.adal.Discovery.validateAuthority(Discovery.java:141) 
        at com.microsoft.aad.adal.AcquireTokenRequest.validateAuthority(AcquireTokenRequest.java:306) 
        at com.microsoft.aad.adal.AcquireTokenRequest.performAuthorityValidation(AcquireTokenRequest.java:216) 
        at com.microsoft.aad.adal.AcquireTokenRequest.validateAcquireTokenRequest(AcquireTokenRequest.java:184) 
        at com.microsoft.aad.adal.AcquireTokenRequest.access$100(AcquireTokenRequest.java:53) 
        at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:122) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569) 
        at java.lang.Thread.run(Thread.java:856) 

- I get this problem and the authentication exception code is: DEVELOPER_AUTHORITY_IS_NOT_VALID_INSTANCE
- I testing LifeTouch L on android 4.0.3, API 15, and the version of adal is 1.15.1.

**Comment by iambmelt** [comment]
Hi @Phanqui2020 We do not support API 15 (minSdk is 16 for our previous releases).

Please upgrade your ADAL version (see [releases](https://github.com/AzureAD/azure-activedirectory-library-for-android/releases)) as well as raise your minSdk to a supported level
