### ISSUE TITLE
Crash report: JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING 

### ISSUE THREAD

**Issue by NgWaiKong** [AzureAD/azure-activedirectory-library-for-android#1640]
Hi, we'd like to report a crash which we captured .
we're using `com.microsoft.aad:adal 3.1.3` 

```
--------- beginning of crash
09-01 20:23:09.393 E/AndroidRuntime(14240): FATAL EXCEPTION: pool-20-thread-1
09-01 20:23:09.393 E/AndroidRuntime(14240): Process: com.microsoft.office.outlook, PID: 14240
09-01 20:23:09.393 E/AndroidRuntime(14240): com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:13)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.google.gson.Gson.i(SourceFile:6)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.google.gson.Gson.k(SourceFile:2)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.google.gson.Gson.m(SourceFile:2)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.google.gson.Gson.l(SourceFile:1)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.DefaultTokenCacheStore.getItem(SourceFile:4)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AuthenticationContext$1.getItem(SourceFile:1)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.TokenCacheAccessor.getRegularRefreshTokenCacheItem(SourceFile:3)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.TokenCacheAccessor.getATFromCache(SourceFile:1)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(SourceFile:4)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(SourceFile:3)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(SourceFile:4)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(SourceFile:3)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(SourceFile:1)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(SourceFile:1)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(SourceFile:4)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at java.lang.Thread.run(Thread.java:764)
09-01 20:23:09.393 E/AndroidRuntime(14240): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.google.gson.stream.JsonReader.b(SourceFile:5)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(SourceFile:4)
09-01 20:23:09.393 E/AndroidRuntime(14240): 	... 18 more
09-01 20:24:09.414 E/AndroidRuntime(15202): FATAL EXCEPTION: pool-17-thread-1
```

Would you mind taking a look on it? please let me know if anything i can help with.

**Comment by paulkagiri** [comment]
Hello @NgWaiKong, are you still experiencing this?
