### ISSUE TITLE
Crash Report : java.lang.IllegalArgumentException getAuthToken not supported

### ISSUE THREAD

**Issue by WenlongRuan** [AzureAD/azure-activedirectory-library-for-android#1652]
Hi, I'm from `Microsoft Launcher` team and we've got several crash reports from our user.
We're using `com.microsoft.aad:adal 3.1.1`
```
Start Date: 2021-10-10T21:38:56.081Z
Date: 2021-10-10T21:39:37.592Z

java.lang.IllegalArgumentException: getAuthToken not supported
  at android.os.Parcel.readException(Parcel.java:1687)
  at android.os.Parcel.readException(Parcel.java:1636)
  at com.microsoft.aad.adal.IBrokerAccountService$Stub$Proxy.acquireTokenSilently(IBrokerAccountService.java:176)
  at com.microsoft.aad.adal.BrokerAccountServiceHandler$2.onSuccess(BrokerAccountServiceHandler.java:137)
  at com.microsoft.aad.adal.BrokerAccountServiceHandler$2.onSuccess(BrokerAccountServiceHandler.java:132)
  at com.microsoft.aad.adal.BrokerAccountServiceHandler$5$1.run(BrokerAccountServiceHandler.java:336)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)

```

**Comment by paulkagiri** [comment]
@hawoyi would you mind providing some more information to enable us reproduce this issue? Versions? Steps?
