### ISSUE TITLE
Facing erros related to "cryptography" library when execute in CentOS 7  Python 3.6.12

### ISSUE THREAD

**Issue by dinocherian** [AzureAD/azure-activedirectory-library-for-android#1688]
"cryptography" library when execute in CentOS 7  Python 3.6.12
Tried with different versions of cryptography library from https://pypi.org/project/cryptography/3.3/#files, but getting same error
Can someone please guide regarding which all versions of libraries should be used in CentOS 7 to make this work?
Thanks in advance.
 
[root@cherid23]# python3 adalp.py input.json
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/hashlib.py", line 274, in <module>
    func = __get_hash(__func_name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/hashlib.py", line 156, in __get_openssl_constructor
    return __get_builtin_constructor(name)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/hashlib.py", line 136, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/jwt/utils.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
Traceback (most recent call last):
  File "adalp.py", line 6, in <module>
    from office365audit.newLib import adal
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/__init__.py", line 34, in <module>
    from .authentication_context import AuthenticationContext
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/authentication_context.py", line 31, in <module>
    from .authority import Authority
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/authority.py", line 39, in <module>
    from . import util
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/util.py", line 35, in <module>
    import adal
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/__init__.py", line 34, in <module>
    from .authentication_context import AuthenticationContext
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/authentication_context.py", line 34, in <module>
    from .token_request import TokenRequest
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/token_request.py", line 34, in <module>
    from . import self_signed_jwt
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/adal/self_signed_jwt.py", line 35, in <module>
    import jwt
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/jwt/__init__.py", line 1, in <module>
    from .api_jwk import PyJWK, PyJWKSet
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/jwt/api_jwk.py", line 3, in <module>
    from .algorithms import get_default_algorithms
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/jwt/algorithms.py", line 6, in <module>
    from .utils import (
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/jwt/utils.py", line 6, in <module>
    from cryptography.hazmat.primitives.asymmetric.ec import EllipticCurve
  File "/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/cryptography/hazmat/primitives/asymmetric/ec.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import (
  File **"/etc/netwitness/ng/logcollection/content/collection/cmdscript/office365audit/newLib/cryptography/hazmat/primitives/asymmetric/utils.py", line 6, in <module>
    from cryptography.hazmat.bindings._rust import asn1**

**Comment by dinocherian** [comment]
Intended to post it in python related issues.
