### ISSUE TITLE
Leaked window

### ISSUE THREAD

**Issue by neosimsim** [AzureAD/azure-activedirectory-library-for-android#355]
Occasionally I get the following error message in log cat after closing the login AuthenticationActivity:
```
03-11 14:21:53.353  13037-13037/de.example.nasrallah.rms E/WindowManager﹕ android.view.WindowLeaked: Activity com.microsoft.aad.adal.AuthenticationActivity has leaked window android.widget.ZoomButtonsController$Container{2d3d94ca V.E..... ......I. 0,0-2048,97} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:261)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.widget.ZoomButtonsController.setVisible(ZoomButtonsController.java:370)
            at com.android.org.chromium.android_webview.AwZoomControls.invokeZoomPicker(AwZoomControls.java:29)
            at com.android.org.chromium.content.browser.ContentViewCore.onScrollBeginEventAck(ContentViewCore.java:1270)
            at com.android.org.chromium.content.browser.ContentViewCore.nativeOnTouchEvent(Native Method)
            at com.android.org.chromium.content.browser.ContentViewCore.onTouchEvent(ContentViewCore.java:1208)
            at com.android.org.chromium.android_webview.AwContents$AwViewMethodsImpl.onTouchEvent(AwContents.java:2312)
            at com.android.org.chromium.android_webview.AwContents.onTouchEvent(AwContents.java:1698)
            at com.android.webview.chromium.WebViewChromium.onTouchEvent(WebViewChromium.java:1910)
            at android.webkit.WebView.onTouchEvent(WebView.java:2286)
            at android.view.View.dispatchTouchEvent(View.java:8388)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2424)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2314)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1692)
            at android.app.Activity.dispatchTouchEvent(Activity.java:2739)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2275)
            at android.view.View.dispatchPointerEvent(View.java:8578)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4021)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3887)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3578)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3635)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3502)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3468)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3476)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3449)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5701)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5675)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5646)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5791)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
            at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
            at android.vie
```
I start the login prompt using the following code.
```Java
    @Override
    public void getToken(Map<String, String> authenticationParametersMap, final AuthenticationCompletionCallback authenticationCompletionCallback) {
        Log.d(this.getClass().getName(), "getToken");
        String authority = authenticationParametersMap.get("oauth2.authority");
        String resource = authenticationParametersMap.get("oauth2.resource");
        String userId = authenticationParametersMap.get("userId");
        String userHint = (userId == null ? "" : userId);

        AuthenticationContext authenticationContext;
        try {
            authenticationContext = getNewAuthenticationContext(authority);
            authenticationContext.acquireToken(mActivity, resource, mClientId, mRedirectURI, userId, mPromptBehavior, "&USERNAME=" + userHint, new AuthenticationCallback<AuthenticationResult>() {
                @Override
                public void onSuccess(AuthenticationResult authenticationResult) {
                    Log.d("RMS", "onSuccess");
                    authenticationCompletionCallback.onSuccess(authenticationResult.getAccessToken());
                }

                @Override
                public void onError(Exception e) {
                    Log.d("RMS", "onError");
                    if (e instanceof AuthenticationCancelError) {
                        authenticationCompletionCallback.onCancel();
                    } else {
                        authenticationCompletionCallback.onFailure();
                    }
                }
            });
        } catch (MuHException e) {
            e.printStackTrace();
            NotificationDialog.show(e.getMessage());
        }
    }

    private AuthenticationContext getNewAuthenticationContext(String authority) throws MuHException{
        AuthenticationContext authenticationContext;
        try {
            authenticationContext = new AuthenticationContext(mActivity, authority, false);
            return authenticationContext;
        } catch (NoSuchAlgorithmException | NoSuchPaddingException e) {
            e.printStackTrace();
            throw new MuHException(e);
        }
    }
```

I'm having some other issues to so I'm not entirely sure if I'm using ADAL wrong.

**Comment by omercs** [comment]
Do you still get this issue after implementing onActivityResult?

**Comment by neosimsim** [comment]
Yes i did. Sorry I can't be more precise. I'll try to find out how to reproduce this issue deterministic. But it's a really rare one.

**Comment by Stinger07** [comment]
Did you ever find a solution to this issue? I am running nearly the same code snippet and having the same issue.

**Comment by weijjia** [comment]
Do you still see the issue? Close for now, can you please re-open if you see the issue again?
