### ISSUE TITLE
Crash in AuthenticationActivity.displaySpinner() during sign-in on OneDrive app

### ISSUE THREAD

**Issue by hanselip** [AzureAD/azure-activedirectory-library-for-android#360]
java.lang.IllegalArgumentException: View not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:383)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:285)
       at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
       at android.app.Dialog.dismissDialog(Dialog.java:323)
       at android.app.Dialog.dismiss(Dialog.java:306)
       at com.microsoft.aad.adal.AuthenticationActivity.displaySpinner()
       at com.microsoft.aad.adal.AuthenticationActivity.access$300()
       at com.microsoft.aad.adal.AuthenticationActivity$CustomWebViewClient.onPageFinished()
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:323)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5039)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by omercs** [comment]
What version of adal are you using? Can you include the log?

**Comment by hanselip** [comment]
We're using version 1.0.9. Unfortunately I don't have the ADAL logs since we don't collect them in our app yet, I only have the trace above from Crashlytics. From the crash data, this has only been seen on devices running Android 4.

**Comment by omercs** [comment]
Is it Android 4.0? What is the device type?  I need to repro on a device if possible. 

Adal checks if activity is finishing or not before dismissing the dialog. I will play with developer options for activity lifecycle to repro this.

**Comment by hanselip** [comment]
We've seen hits on Android 4.0.4, 4.1.2, 4.2.2 and across devices (mostly Samsung S3, Samsung Ace). Thanks for taking a look, I'll try and get a live repro as well.

**Comment by omercs** [comment]
Can you try the fix at https://github.com/AzureAD/azure-activedirectory-library-for-android/tree/fix_spinner_dismiss ?

**Comment by weijjia** [comment]
Please re-open if you see the issue again.
