### ISSUE TITLE
ANDROIDKEYSTORE_FAILED error when using API 23 version

### ISSUE THREAD

**Issue by davechmsft** [AzureAD/azure-activedirectory-library-for-android#412]
We discovered when running our sample (https://github.com/OfficeDev/O365-Android-Start) using Android API version 23 that ADAL throws an error when generating the secret key. API 23 is in preview, but thought you should know this is happening.

Below is the error we are seeing:

```java
08-21 16:49:20.517  17273-17386/com.microsoft.office365.starter E/StorageHelper﹕ ANDROIDKEYSTORE_FAILED:2015-08-21 09:49:20-4f775c58-2a4d-4b31-a191-15f87d3e3b73-Failed to get private key from AndroidKeyStore ver:1.1.2
java.lang.IllegalStateException: could not generate key in keystore
        at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:100)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:275)
        at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:525)
        at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:447)
        at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:163)
        at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:275)
        at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:104)
        at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:179)
        at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1472)
        at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1452)
        at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:58)
        at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:818)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
08-21 16:49:20.527  17273-17386/com.microsoft.office365.starter E/DefaultTokenCacheStore﹕ ENCRYPTION_FAILED:2015-08-21 09:49:20-4f775c58-2a4d-4b31-a191-15f87d3e3b73-Encryption failure ver:1.1.2
java.lang.IllegalArgumentException: rawBytes
        at com.microsoft.aad.adal.StorageHelper.getSecretKey(StorageHelper.java:229)
        at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:174)
        at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:275)
        at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:104)
        at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:179)
        at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1472)
        at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1452)
        at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:58)
        at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:818)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by iambmelt** [comment]
Adding some additional information to this issue...

Per feedback in [this issue](https://github.com/OfficeDev/O365-Android-Start/issues/9), this was triggered on a Samsung Galaxy S4 running 4.4.4 (API 19)

**Comment by weijjia** [comment]
Do you have the verbose logging for ADAL? It will help me to investigate the cause of this.

**Comment by iambmelt** [comment]
@weijjia Off-hand, I've not got the logs. If needed they can be regenerated by executing the ADAL call on an API 23 emulator. :+1: If you're unable to repro just let @davechmsft or me know and we'll see how we can help.

**Comment by weijjia** [comment]
ok, thanks. I'll try to repro it on the emulator.

**Comment by weijjia** [comment]
@iambmelt and @davechmsft , I run a sample test on the API 23 emulator but i'm not able to repro it. If you could repro on your side, please send me the logs. That will be helpful.

**Comment by iambmelt** [comment]
@weijjia Ok. I'll shoot to get logs your way on Tuesday if I'm able to repro. 

Thanks!

/cc @davechmsft

**Comment by iambmelt** [comment]
@weijjia Retested on the latest API 23 emulator images for ```x86_64``` and wasn't able to repro. Feel free to close.

**Comment by weijjia** [comment]
Thanks for the update.
