### ISSUE TITLE
Window Leak

### ISSUE THREAD

**Issue by Stinger07** [AzureAD/azure-activedirectory-library-for-android#415]
I have an error when I call the aquireToken method of my AuthenticationContext, I am getting a window leak issue in my Logs.  The exact log is as follows: 

08-31 09:17:45.309  30259-30259/com.ford.mcross48.oauth2test E/WindowManager﹕ android.view.WindowLeaked: Activity com.microsoft.aad.adal.AuthenticationActivity has leaked window org.chromium.content.browser.input.PopupTouchHandleDrawable{1d6b9fc7 V.ED.... ........ 0,0-70,84} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
            at android.widget.PopupWindow.invokePopup(PopupWindow.java:1104)
            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:933)
            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:897)
            at org.chromium.content.browser.input.PopupTouchHandleDrawable.show(PopupTouchHandleDrawable.java:354)
            at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
            at org.chromium.android_webview.AwContents.access$4500(AwContents.java:92)
            at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:2731)
            at org.chromium.android_webview.AwContents.onDraw(AwContents.java:1191)
            at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:1601)
            at android.webkit.WebView.onDraw(WebView.java:2393)
            at android.view.View.draw(View.java:15231)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Because this happens, I get no callbacks for onSuccess and onFailure, and thus I am not authenticating properly.

**Comment by leofirespotter** [comment]
@Stinger07 how did you solve this?

**Comment by Stinger07** [comment]
You must add an onActivityResult method to your main activity that calls the onActivityResult of the Authentication Activity:

    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (mAuthContext != null) {
            mAuthContext.onActivityResult(requestCode, resultCode, data);
        }
    }

**Comment by leofirespotter** [comment]
@Stinger07 hm I already had that. Off of what sample code are you working? I have the same issue over here https://github.com/Azure-Samples/active-directory-android/issues/9

**Comment by CarlosMAguilar** [comment]
The answer is unclear to me, can anyone help me? I also have that onActivityResult function at CordovaAdalPlugin.java. I am able to get token and everything works fine but I am having that issue in console.

**Comment by LoveqLRC** [comment]
a)
`protected void onDestroy() {
        super.onDestroy();
        mWeb.setVisibility(View.GONE); 
}`

b)
`
public void finish() {  
    ViewGroup view = (ViewGroup) getWindow().getDecorView();  
    view.removeAllViews();  
    super.finish();  
}
`
It works for me
