### ISSUE TITLE
AuthenticationActivity has leaked window org.chromium.content.browser.input.PopupTouchHandleDrawable

### ISSUE THREAD

**Issue by leofirespotter** [AzureAD/azure-activedirectory-library-for-android#433]
When running any of the sample apps I get the following crash (also happens in my app):
```
09-24 11:18:10.091      314-314/com.microsoft.aad.taskapplication E/WindowManager﹕ android.view.WindowLeaked: Activity com.microsoft.aad.adal.AuthenticationActivity has leaked window org.chromium.content.browser.input.PopupTouchHandleDrawable{3d923a03 V.ED.... ........ 0,0-141,174} that was originally added here
            at android.view.ViewRootImpl.<init>(ViewRootImpl.java:363)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
            at android.widget.PopupWindow.invokePopup(PopupWindow.java:1104)
            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:933)
            at android.widget.PopupWindow.showAtLocation(PopupWindow.java:897)
            at org.chromium.content.browser.input.PopupTouchHandleDrawable.show(PopupTouchHandleDrawable.java:354)
            at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
            at org.chromium.android_webview.AwContents.access$4100(AwContents.java:94)
            at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:2729)
            at org.chromium.android_webview.AwContents.onDraw(AwContents.java:1180)
            at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:1718)
            at android.webkit.WebView.onDraw(WebView.java:2393)
            at android.view.View.draw(View.java:15231)
            at android.view.View.updateDisplayListIfDirty(View.java:14167)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3389)
            at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3368)
            at android.view.View.updateDisplayListIfDirty(View.java:14127)
            at android.view.View.getDisplayList(View.java:14189)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by weijjia** [comment]
Which adal version are you on?

**Comment by leofirespotter** [comment]
1.1.9

**Comment by weijjia** [comment]
Did you see any of the similar issue before you switch to 1.1.9?

**Comment by leofirespotter** [comment]
Yes I've been having this issue for a bit now

**Comment by weijjia** [comment]
Thanks for the info. I'll try to repro on my side. If not, i'll then ask for more detailed logs from you.

**Comment by leofirespotter** [comment]
Confirmed to still be crashing on 1.1.10

**Comment by addev-ashish** [comment]
@leofirespotter Do you still hit this. If yes, kindly reactivate with the latest SDK with which you tried this. Thanks.
