### ISSUE TITLE
Failed to generate self-signed certificate when using Arabic Language

### ISSUE THREAD

**Issue by sgrebnov** [AzureAD/azure-activedirectory-library-for-android#549]
When I set Arabic language in settings authorization is successful and callback is called with correct token. But token is not persist in the cache due to the following error:

```
.IllegalArgumentException: invalid date string: Unparseable date: "ñöðóñ÷ñõóøñöGMT+00:00" (at offset 0)
```

```
03-17 11:38:16.367 28352-28409/com.example.serge.myapplication V/HttpWebRequest: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Status code:200 ver:1.1.12
03-17 11:38:16.369 28352-28409/com.example.serge.myapplication V/HttpWebRequest: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Response is received ver:1.1.12
03-17 11:38:16.369 28352-28409/com.example.serge.myapplication V/Oauth: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Token request does not have exception ver:1.1.12
03-17 11:38:16.371 28352-28409/com.example.serge.myapplication V/Oauth: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-IdToken is extracted from token response ver:1.1.12
03-17 11:38:16.371 28352-28409/com.example.serge.myapplication V/Oauth: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Response correlationId:edc820ba-63df-49d8-832d-f213b60a5d4c ver:1.1.12
03-17 11:38:16.372 28352-28409/com.example.serge.myapplication V/AuthenticationContext: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-OnActivityResult processed the result. Request authority:https://login.windows.net/test353.onmicrosoft.com resource:https://graph.windows.net/ clientid:1eed60fd-93bf-44c3-948b-d419b32b5ed6 ver:1.1.12
03-17 11:38:16.373 28352-28409/com.example.serge.myapplication V/AuthenticationContext: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-OnActivityResult is setting the token to cache. Request authority:https://login.windows.net/test353.onmicrosoft.com resource:https://graph.windows.net/ clientid:1eed60fd-93bf-44c3-948b-d419b32b5ed6 ver:1.1.12
03-17 11:38:16.373 28352-28409/com.example.serge.myapplication V/AuthenticationContext: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Setting item to cache ver:1.1.12
03-17 11:38:16.375 28352-28409/com.example.serge.myapplication V/AuthenticationContext: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Access TokenID YQCjorawMYiRrO5lwb0j+ofkoWS9WJDkLhlZuRQSpFk= and Refresh TokenID HVFu7fRF5L3EQrO4L2r8ujISIvsWmMZHNksdGdh4T04= returned. CorrelationId: edc820ba-63df-49d8-832d-f213b60a5d4c ver:1.1.12
03-17 11:38:16.375 28352-28409/com.example.serge.myapplication V/AuthenticationContext: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Updating cache for username:localuser@test353.onmicrosoft.com ver:1.1.12
03-17 11:38:16.387 28352-28409/com.example.serge.myapplication V/StorageHelper: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Starting encryption ver:1.1.12
03-17 11:38:16.389 28352-28409/com.example.serge.myapplication V/StorageHelper: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Key entry is not available ver:1.1.12
03-17 11:38:16.788 28352-28409/com.example.serge.myapplication E/StorageHelper: ANDROIDKEYSTORE_FAILED:۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Failed to get private key from AndroidKeyStore ver:1.1.12 
                                                                                java.security.ProviderException: Failed to generate self-signed certificate
                                                                                    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:504)
                                                                                    at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
                                                                                    at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:525)
                                                                                    at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:447)
                                                                                    at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:163)
                                                                                    at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:275)
                                                                                    at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:107)
                                                                                    at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:182)
                                                                                    at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1506)
                                                                                    at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1486)
                                                                                    at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:58)
                                                                                    at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:828)
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                    at java.lang.Thread.run(Thread.java:818)
                                                                                 Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "ñöðóñ÷ñõóøñöGMT+00:00" (at offset 0)
                                                                                    at com.android.org.bouncycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
                                                                                    at com.android.org.bouncycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:23)
                                                                                    at com.android.org.bouncycastle.asn1.x509.Time.<init>(Time.java:67)
                                                                                    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateWithFakeSignature(AndroidKeyStoreKeyPairGeneratorSpi.java:618)
                                                                                    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate(AndroidKeyStoreKeyPairGeneratorSpi.java:565)
                                                                                    at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:502)
                                                                                    at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276) 
                                                                                    at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:525) 
                                                                                    at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:447) 
                                                                                    at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:163) 
                                                                                    at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:275) 
                                                                                    at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:107) 
                                                                                    at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:182) 
                                                                                    at com.microsoft.aad.adal.AuthenticationContext.setItemToCacheForUser(AuthenticationContext.java:1506) 
                                                                                    at com.microsoft.aad.adal.AuthenticationContext.setItemToCache(AuthenticationContext.java:1486) 
                                                                                    at com.microsoft.aad.adal.AuthenticationContext.access$300(AuthenticationContext.java:58) 
                                                                                    at com.microsoft.aad.adal.AuthenticationContext$3.run(AuthenticationContext.java:828) 
                                                                                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                                    at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                                    at java.lang.Thread.run(Thread.java:818) 
03-17 11:38:16.788 28352-28409/com.example.serge.myapplication V/StorageHelper: ۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Encryption will use secret key from Settings ver:1.1.12
03-17 11:38:16.788 28352-28409/com.example.serge.myapplication E/DefaultTokenCacheStore: ENCRYPTION_FAILED:۲۰۱۶-۰۳-۱۷ ۱۵:۳۸:۱۶-200c79bf-699e-4594-bc64-88e874485069-Encryption failure ver:1.1.12 
```

The problem only appears when the phone is localized in Arabic (ADAL version 1.1.12 ; tested on android 6.0.0)

**Comment by murki** [comment]
+1 seeing this in our crash logs as well.

**Comment by almost92** [comment]
+1 
@weijjia any update on this ?

**Comment by weijjia** [comment]
Please check the wiki https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
