### ISSUE TITLE
Android N SDK

### ISSUE THREAD

**Issue by bschnack** [AzureAD/azure-activedirectory-library-for-android#596]
Hello,

I tried running this on the new Android N SDK Emulator and I crash every time I launch Adal with:
04-19 14:16:39.028 E/AndroidRuntime: FATAL EXCEPTION: main
                                     Process: ols.microsoft.com.shiftr.dev, PID: 5056
                                     java.lang.AbstractMethodError: abstract method "android.os.Handler android.webkit.WebViewProvider$ViewDelegate.getHandler(android.os.Handler)"
                                         at android.webkit.WebView.getHandler(WebView.java:2628)
                                         at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1155)
                                         at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1370)
                                         at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3568)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:148)
                                         at android.app.ActivityThread.main(ActivityThread.java:6066)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:770)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:660)

Thanks,
Brian

**Comment by weijjia** [comment]
@bschnack Are you already start integrating with N? N is only in preview 2 now, and planned for release in Q3. I don't think we're going to support it now. But we'll look into it and get back to you. Thanks a lot.

**Comment by addev-ashish** [comment]
@bschnack we will look at N when its closer to release and update our SDK then. Thanks for bringing this up.
