### ISSUE TITLE
Runtime exceptions thrown by keystore

### ISSUE THREAD

**Issue by weijjia** [AzureAD/azure-activedirectory-library-for-android#614]
Following are the top crashes thrown by keystore currently reported by outlook:

- 1. 

```
java.lang.IllegalStateException: could not generate key in keystore
       at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:99)
       at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
       at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:488)
       at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:416)
       at com.microsoft.aad.adal.StorageHelper.getKeyForVersion(StorageHelper.java:190)
       at com.microsoft.aad.adal.StorageHelper.decrypt(StorageHelper.java:259)
       at com.microsoft.aad.adal.DefaultTokenCacheStore.decrypt(DefaultTokenCacheStore.java:127)
       at com.microsoft.aad.adal.DefaultTokenCacheStore.getItem(DefaultTokenCacheStore.java:145)
       at com.microsoft.aad.adal.AuthenticationContext.getItemFromCache(AuthenticationContext.java:1503)
       at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1381)
       at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1373)
       at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1200)
       at com.microsoft.aad.adal.AuthenticationContext.access$600(AuthenticationContext.java:62)
       at com.microsoft.aad.adal.AuthenticationContext$6.run(AuthenticationContext.java:1159)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

- 2. 

```
java.lang.NullPointerException: Attempt to invoke interface method 'int android.security.IKeystoreService.exist(java.lang.String, int)' on a null object reference
       at android.security.KeyStore.contains(KeyStore.java:195)
       at android.security.KeyStore.contains(KeyStore.java:203)
       at android.security.keystore.AndroidKeyStoreSpi.engineContainsAlias(AndroidKeyStoreSpi.java:803)
       at java.security.KeyStore.containsAlias(KeyStore.java:442)
       at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:473)
       at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:416)
       at com.microsoft.aad.adal.StorageHelper.getKeyForVersion(StorageHelper.java:190)
       at com.microsoft.aad.adal.StorageHelper.decrypt(StorageHelper.java:259)
       at com.microsoft.aad.adal.DefaultTokenCacheStore.decrypt(DefaultTokenCacheStore.java:127)
       at com.microsoft.aad.adal.DefaultTokenCacheStore.getItem(DefaultTokenCacheStore.java:145)
       at com.microsoft.aad.adal.AuthenticationContext.getRefreshToken(AuthenticationContext.java:1601)
       at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1396)
       at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1373)
       at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1200)
       at com.microsoft.aad.adal.AuthenticationContext.access$100(AuthenticationContext.java:62)
                                                 access$200
                                                 access$300
                                                 access$400
                                                 access$600
                                                 access$900
                                                 access$1000
       at com.microsoft.aad.adal.AuthenticationContext$6.run(AuthenticationContext.java:1159)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

- 3. 

```
java.lang.IllegalArgumentException: key.length == 0
       at javax.crypto.spec.SecretKeySpec.<init>(SecretKeySpec.java:62)
       at com.android.org.conscrypt.OpenSSLCipherRSA.engineUnwrap(OpenSSLCipherRSA.java:333)
       at javax.crypto.Cipher.unwrap(Cipher.java:1409)
       at com.microsoft.aad.adal.StorageHelper.unwrap(StorageHelper.java:576)
       at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:436)
       at com.microsoft.aad.adal.StorageHelper.getKeyForVersion(StorageHelper.java:190)
       at com.microsoft.aad.adal.StorageHelper.decrypt(StorageHelper.java:259)
       at com.microsoft.aad.adal.DefaultTokenCacheStore.decrypt(DefaultTokenCacheStore.java:127)
       at com.microsoft.aad.adal.DefaultTokenCacheStore.getItem(DefaultTokenCacheStore.java:145)
       at com.microsoft.aad.adal.AuthenticationContext.getItemFromCache(AuthenticationContext.java:1503)
       at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1381)
       at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1373)
       at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1200)
       at com.microsoft.aad.adal.AuthenticationContext.access$100(AuthenticationContext.java:62)
                                                 access$200
                                                 access$300
                                                 access$400
                                                 access$600
                                                 access$900
                                                 access$1000
       at com.microsoft.aad.adal.AuthenticationContext$6.run(AuthenticationContext.java:1159)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

```
Based on the current investigation we have around keystore, here is the current issues and can potentially cause all the above exceptions thrown across different os versions. 
1) keystore can be locked under a lock screen, if we try to access keystore when it's locked, the behavior is undefined. 
2) Keystore is protected by the lock screen protection, i.e. pincode or pattern, if any of then change, keystore can be wiped out. 

To best protect the app from crashing from the above runtime exceptions, we'll catch those individual exceptions, and re-throw checked exceptions.

**Comment by weijjia** [comment]
Fixed in PR 615. Closed.
