### ISSUE TITLE
Failed to get private key from AndroidKeyStore on Meizu MX4 pro

### ISSUE THREAD

**Issue by yucaowang** [AzureAD/azure-activedirectory-library-for-android#673]
**Device**: Meizu MX4 pro
**OS**: Android 5.1.1 (Flyme 5.1.7.0A)
**Description**: Got ANDROIDKEYSTORE_FAILED exception when creating AuthenticationContext.
**Code**:   mAuthenticationContext =
                        new AuthenticationContext(
                                mContextActivity,
                                Constants.AAD_AUTHORITY_URL,
                                false
                        );
**Call stack**:
E/StorageHelper: ANDROIDKEYSTORE_FAILED:2016-07-06 12:02:25-null-Failed to get private key from AndroidKeyStore ver:1.2.1 
    java.security.KeyStoreException: java.lang.IllegalStateException: could not generate key in keystore
        at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:528)
        at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:426)
        at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:168)
        at com.microsoft.aad.adal.DefaultTokenCacheStore.<init>(DefaultTokenCacheStore.java:103)
        at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:152)
        at com.lazyyuc.moonchat.utils.AuthenticationManager.getAuthenticationContext(AuthenticationManager.java:258)
        at com.lazyyuc.moonchat.utils.AuthenticationManager.authenticatePrompt(AuthenticationManager.java:204)
        at com.lazyyuc.moonchat.utils.AuthenticationManager.connect(AuthenticationManager.java:118)
        at com.lazyyuc.moonchat.fragments.LoginFragment.onActivityCreated(LoginFragment.java:66)
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2083)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1129)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671)
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239)
        at android.app.Activity.performStart(Activity.java:6069)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2546)
        at android.app.ActivityThread.access$800(ActivityThread.java:154)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5453)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
     Caused by: java.lang.IllegalStateException: could not generate key in keystore
        at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:99)
        at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
        at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:517)
        at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:426) 
        at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:168) 
        at com.microsoft.aad.adal.DefaultTokenCacheStore.<init>(DefaultTokenCacheStore.java:103) 
        at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:152) 
        at com.lazyyuc.moonchat.utils.AuthenticationManager.getAuthenticationContext(AuthenticationManager.java:258) 
        at com.lazyyuc.moonchat.utils.AuthenticationManager.authenticatePrompt(AuthenticationManager.java:204) 
        at com.lazyyuc.moonchat.utils.AuthenticationManager.connect(AuthenticationManager.java:118) 
        at com.lazyyuc.moonchat.fragments.LoginFragment.onActivityCreated(LoginFragment.java:66) 
        at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:2083) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1129) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286) 
        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1671) 
        at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:619) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1239) 
        at android.app.Activity.performStart(Activity.java:6069) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2447) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2546) 
        at android.app.ActivityThread.access$800(ActivityThread.java:154) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1430) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5453) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:952) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)

**Comment by khalidaw** [comment]
+1 we see this a lot in telemetry

**Comment by brucemax** [comment]
+1 on Sumsung with android 4.4.2, when trying tokenCache.serialize() method

**Comment by hjymandroid** [comment]
+1 we also see a lot of this.

**Comment by weijjia** [comment]
Please check the wiki https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
