### ISSUE TITLE
Not able to resolve dependency

### ISSUE THREAD

**Issue by aryasunny** [AzureAD/azure-activedirectory-library-for-android#692]
Hi,

I am trying to use adal dependency in my project as I need to use these libraries for authenticating with MsAzure. I took the below dependency

```
<dependency>
	<groupId>com.microsoft.aad</groupId>
	<artifactId>adal</artifactId>
	<version>1.2.1</version>
</dependency>
```

But I am not able to resolve this dependency using maven. I am getting the below error.

```
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project org.springframework:bamboo-collector:jar:0.1.0: Failed to
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:180)
        at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
        ... 23 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.microsoft.aad:adal:jar:1.2.1 -> com.android.support:suppo
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
        at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:172)
        ... 24 more
Caused by: org.eclipse.aether.resolution.VersionRangeResolutionException: No versions available for com.android.support:support-v4:jar:[21,) within specified range
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.filterVersions(DefaultDependencyCollector.java:648)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:394)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:504)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        ... 26 more
```

I believe I am not using the correct repository. Can someone please help me with this.

**Comment by weijjia** [comment]
You need to put <type>aar</type> in your dependency.

**Comment by weijjia** [comment]
Close the issue for now. Re-open it when you see it again.
