### ISSUE TITLE
Outlook crash from NullPointerException during silent flow

### ISSUE THREAD

**Issue by weijjia** [AzureAD/azure-activedirectory-library-for-android#695]
Stacktrace from outlook. During silent flow, if the token item we store doesn't contain the refresh token, null pointer will be thrown when building the post request message with grant type as refresh_token. 

java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
      at libcore.net.UriCodec.encode(UriCodec.java:132)
      at java.net.URLEncoder.encode(URLEncoder.java:57)
      at com.microsoft.aad.adal.StringExtensions.URLFormEncode(StringExtensions.java:83)
      at com.microsoft.aad.adal.Oauth2.buildRefreshTokenRequestMessage(Oauth2.java:177)
      at com.microsoft.aad.adal.Oauth2.refreshToken(Oauth2.java:302)
      at com.microsoft.aad.adal.AcquireTokenSilentHandler.acquireTokenWithRefreshToken(AcquireTokenSilentHandler.java:126)
      at com.microsoft.aad.adal.AcquireTokenSilentHandler.acquireTokenWithCachedItem(AcquireTokenSilentHandler.java:269)
      at com.microsoft.aad.adal.AcquireTokenSilentHandler.useMRRT(AcquireTokenSilentHandler.java:261)
      at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryMRRT(AcquireTokenSilentHandler.java:203)
      at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryRT(AcquireTokenSilentHandler.java:161)
      at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(AcquireTokenSilentHandler.java:104)
      at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1461)
      at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1448)
      at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1261)
      at com.microsoft.aad.adal.AuthenticationContext.access$900(AuthenticationContext.java:73)
      at com.microsoft.aad.adal.AuthenticationContext$7.run(AuthenticationContext.java:1220)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
      at java.lang.Thread.run(Thread.java:818)

**Comment by weijjia** [comment]
Fixed with PR #699
