### ISSUE TITLE
IllegalArgumentException when trying to create AuthenticationContext in Arabic locale

### ISSUE THREAD

**Issue by dbahat** [AzureAD/azure-activedirectory-library-for-android#706]
Seeing the following issue when trying to create AuthenticationContext using the DefaultTokenCacheStore, when the device locale is in Arabic or Farsi.

Possible root cause:  StorageHelper.getKeyPairFromAndroidKeyStore() calls Calendar.getInstance() without specifying a locale.

Getting the following exception:
java.lang.IllegalArgumentException: invalid date string: Unparseable date: "
af`hbiac`a`cGMT+00:00" (at offset 0)
at com.android.org.bouncycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:98)
at com.android.org.bouncycastle.asn1.x509.Time.<init>(Time.java:62)
at com.android.org.bouncycastle.x509.X509V3CertificateGenerator.setNotBefore(X509V3CertificateGenerator.java:112)
at android.security.AndroidKeyPairGenerator.generateKeyPair(AndroidKeyPairGenerator.java:127)
at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:517)
at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:426)
at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:168)
at com.microsoft.aad.adal.DefaultTokenCacheStore.<init>(DefaultTokenCacheStore.java:103)
at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:152)

**Comment by heidijinxujia** [comment]
@dbahat Hi, which branch are you using?

**Comment by dbahat** [comment]
Seeing this in release 1.2.0

**Comment by dbahat** [comment]
Seems to be due to an issue in Android. 
Opened issue https://code.google.com/p/android/issues/detail?id=228196

**Comment by hjymandroid** [comment]
Any progress on this bug? It is blocker for us to use ADAL now.

**Comment by weijjia** [comment]
Please check this wiki https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
