### ISSUE TITLE
User gets prompted for password when no network and uses Broker flow

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#707]
Instead of DEVICE_CONNECTION_IS_NOT_AVAILABLE aquire token returns AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED or shows UI.

And actually any error that occures in broker app, adal handles as non retryable error...

**Comment by heidijinxujia** [comment]
Hi @imakhalova , could you paste details of the log here? Thanks.

**Comment by imakhalova** [comment]
Repro steps:
acquire token for 1 resource (using broker flow), turn off network, try acquire token for another resource, you get AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED

You can collect logs on your own as it has 100% repro.

**Comment by heidijinxujia** [comment]
Hi @imakhalova I've tried the steps on the useappwithbroker.apk with adal-1.10.0 on Android N. I first tried to acquire token for a mam account from resource1 (using broker flow) and get the token back from broker (I install AA here as broker) successfully. And turned off network and tried to acquire token for the same account with resource2. It returns DEVICE_CONNECTION_IS_NOT_AVAILABLE instead of AUTH_REFRESH_FAILED_PROMP_NOT_ALLOWED. Could you give more details of your steps, like test app, adal version and testing account or paste the log here? Because based on the test I did so far, the error code returned is as expected. And the log did not show anything wrong. Thanks.

**Comment by heidijinxujia** [comment]
Do you mean you tried acquireTokenSilent on resource 2 instead of acquireToken? I still didn't get the error you mentioned. Please send me your log. As to the redirectUri, you can see the expected redirectUri from the log if the one you entered is not correct.

**Comment by imakhalova** [comment]
Here is logs:
09-20 15:58:26.693 26769-19525/com.microsoft.skydrive V/PRNGFixes: 2016-09-20 22:58:26-67a47dc2-70c7-45cd-8d67-6041ae2bb18c-No need to apply the fix ver:1.10.0
09-20 15:58:26.693 26769-19525/com.microsoft.skydrive V/[ADAL]PRNGFixes: 2016-09-20 22:58:26-67a47dc2-70c7-45cd-8d67-6041ae2bb18c-No need to apply the fix ver:1.10.0
09-20 15:58:26.694 26769-19525/com.microsoft.skydrive V/PRNGFixes: 2016-09-20 22:58:26-67a47dc2-70c7-45cd-8d67-6041ae2bb18c-No need to apply the fix ver:1.10.0
09-20 15:58:26.695 26769-19525/com.microsoft.skydrive V/[ADAL]PRNGFixes: 2016-09-20 22:58:26-67a47dc2-70c7-45cd-8d67-6041ae2bb18c-No need to apply the fix ver:1.10.0
09-20 15:58:26.698 26769-19525/com.microsoft.skydrive V/AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Sending async task from thread:19525 ver:1.10.0
09-20 15:58:26.700 26769-19525/com.microsoft.skydrive V/[ADAL]AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Sending async task from thread:19525 ver:1.10.0
09-20 15:58:26.701 26769-15446/com.microsoft.skydrive V/AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Running task in thread:15446 ver:1.10.0
09-20 15:58:26.701 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Running task in thread:15446 ver:1.10.0
09-20 15:58:26.707 26769-15446/com.microsoft.skydrive V/AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Try to acquire token silently, return valid AT or use RT in the cache. ver:1.10.0
09-20 15:58:26.708 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Try to acquire token silently, return valid AT or use RT in the cache. ver:1.10.0
09-20 15:58:26.708 26769-15446/com.microsoft.skydrive V/AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Try to silently get token from local cache. ver:1.10.0
09-20 15:58:26.709 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Try to silently get token from local cache. ver:1.10.0
09-20 15:58:26.709 26769-15446/com.microsoft.skydrive V/TokenCacheAccessor: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-No access token exists. ver:1.10.0
09-20 15:58:26.710 26769-15446/com.microsoft.skydrive V/[ADAL]TokenCacheAccessor: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-No access token exists. ver:1.10.0
09-20 15:58:26.710 26769-15446/com.microsoft.skydrive V/AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-No valid access token exists, try with refresh token. ver:1.10.0
09-20 15:58:26.711 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-No valid access token exists, try with refresh token. ver:1.10.0
09-20 15:58:26.711 26769-15446/com.microsoft.skydrive V/AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Regular token cache entry does not exist, try with MRRT. ver:1.10.0
09-20 15:58:26.712 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Regular token cache entry does not exist, try with MRRT. ver:1.10.0
09-20 15:58:26.712 26769-15446/com.microsoft.skydrive V/AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-MRRT token does not exist, try with FRT ver:1.10.0
09-20 15:58:26.713 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-MRRT token does not exist, try with FRT ver:1.10.0
09-20 15:58:26.713 26769-15446/com.microsoft.skydrive V/AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-FRT cache item does not exist, fall back to try MRRT. ver:1.10.0
09-20 15:58:26.713 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-FRT cache item does not exist, fall back to try MRRT. ver:1.10.0
09-20 15:58:26.714 26769-15446/com.microsoft.skydrive V/AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Send request to use MRRT for new AT. ver:1.10.0
09-20 15:58:26.715 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Send request to use MRRT for new AT. ver:1.10.0
09-20 15:58:26.715 26769-15446/com.microsoft.skydrive V/AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-MRRT does not exist, cannot proceed with MRRT for new AT. ver:1.10.0
09-20 15:58:26.715 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenSilentHandler: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-MRRT does not exist, cannot proceed with MRRT for new AT. ver:1.10.0
09-20 15:58:26.718 26769-19168/com.microsoft.skydrive I/com.microsoft.onedrivecore.LogWriterInterface: No new state for item: 4774 (..\..\qt\OneDriveCore\streamcache\streamsyncstate.cpp:81)
09-20 15:58:26.723 26769-15446/com.microsoft.skydrive D/AcquireTokenRequest: Cannot get AT from local cache, switch to Broker for auth, clear tokens from local cache for the user.
09-20 15:58:26.724 26769-15446/com.microsoft.skydrive I/[ADAL]AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Cannot get AT from local cache, switch to Broker for auth, clear tokens from local cache for the user. ver:1.10.0 - 
09-20 15:58:26.725 26769-15446/com.microsoft.skydrive V/AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-No token items need to be deleted for the user. ver:1.10.0
09-20 15:58:26.725 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-No token items need to be deleted for the user. ver:1.10.0
09-20 15:58:26.727 26769-15446/com.microsoft.skydrive I/AcquireTokenWithBrokerRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Broker app is: com.azure.authenticator;Broker app version: VersionName=5.2.0;VersonCode=47. ver:1.10.0 
09-20 15:58:26.728 26769-15446/com.microsoft.skydrive I/[ADAL]AcquireTokenWithBrokerRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Broker app is: com.azure.authenticator;Broker app version: VersionName=5.2.0;VersonCode=47. ver:1.10.0 - 
09-20 15:58:26.728 26769-15446/com.microsoft.skydrive V/AcquireTokenWithBrokerRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-User is specified for background(silent) token request, trying to acquire token silently. ver:1.10.0
09-20 15:58:26.729 26769-15446/com.microsoft.skydrive V/[ADAL]AcquireTokenWithBrokerRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-User is specified for background(silent) token request, trying to acquire token silently. ver:1.10.0
09-20 15:58:26.730 26769-15446/com.microsoft.skydrive V/BrokerProxy:getBrokerUsers: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Retrieve all the accounts from account manager with broker account type, and the account length is: 2 ver:1.10.0
09-20 15:58:26.730 26769-15446/com.microsoft.skydrive V/[ADAL]BrokerProxy:getBrokerUsers: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Retrieve all the accounts from account manager with broker account type, and the account length is: 2 ver:1.10.0
09-20 15:58:26.734 26769-15446/com.microsoft.skydrive V/BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Waiting for userinfo retrieval result from Broker. ver:1.10.0
09-20 15:58:26.735 26769-15446/com.microsoft.skydrive V/[ADAL]BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Waiting for userinfo retrieval result from Broker. ver:1.10.0
09-20 15:58:26.761 26769-19168/com.microsoft.skydrive I/com.microsoft.onedrivecore.LogWriterInterface: No new state for item: 10992 (..\..\qt\OneDriveCore\streamcache\streamsyncstate.cpp:81)
09-20 15:58:26.783 26769-15446/com.microsoft.skydrive V/BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Waiting for userinfo retrieval result from Broker. ver:1.10.0
09-20 15:58:26.783 26769-15446/com.microsoft.skydrive V/[ADAL]BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Waiting for userinfo retrieval result from Broker. ver:1.10.0
09-20 15:58:26.828 26769-15446/com.microsoft.skydrive V/BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Received result from broker ver:1.10.0
09-20 15:58:26.828 26769-15446/com.microsoft.skydrive V/[ADAL]BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Received result from broker ver:1.10.0
09-20 15:58:26.885 26769-15446/com.microsoft.skydrive E/BrokerProxy: BROKER_AUTHENTICATOR_NOT_RESPONDING:2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Authenticator cancels the request ver:1.10.0 
09-20 15:58:26.886 26769-15446/com.microsoft.skydrive E/[ADAL]BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Authenticator cancels the request ver:1.10.0 - 
                                                                           com.microsoft.aad.adal.AuthenticationException: Authenticator is not responding
                                                                               at com.microsoft.authorization.adal.ADALNetworkTasks$2.Log(ADALNetworkTasks.java:93)
                                                                               at com.microsoft.aad.adal.Logger.logCommon(Logger.java:268)
                                                                               at com.microsoft.aad.adal.Logger.error(Logger.java:242)
                                                                               at com.microsoft.aad.adal.Logger.e(Logger.java:381)
                                                                               at com.microsoft.aad.adal.BrokerProxy.getAuthTokenInBackground(BrokerProxy.java:331)
                                                                               at com.microsoft.aad.adal.AcquireTokenWithBrokerRequest.acquireTokenWithBrokerSilent(AcquireTokenWithBrokerRequest.java:65)
                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentWithBroker(AcquireTokenRequest.java:341)
                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(AcquireTokenRequest.java:305)
                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:242)
                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:226)
                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:45)
                                                                               at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:105)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
09-20 15:58:26.886 26769-15446/com.microsoft.skydrive V/BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Returning result from broker ver:1.10.0
09-20 15:58:26.886 26769-15446/com.microsoft.skydrive V/[ADAL]BrokerProxy: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Returning result from broker ver:1.10.0
09-20 15:58:26.887 26769-15446/com.microsoft.skydrive E/AcquireTokenRequest: AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED:2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Prompt is not allowed and failed to get token: ver:1.10.0 Request authority:https://login.windows.net/common resource:https://microsoft.sharepoint.com clientid:b26aadf8-566f-4478-926f-589f601d9c74 No result returned from acquireTokenSilent
09-20 15:58:26.887 26769-15446/com.microsoft.skydrive E/[ADAL]AcquireTokenRequest: 2016-09-20 22:58:26-76e744e6-7072-4516-8692-7405733914fb-Prompt is not allowed and failed to get token: ver:1.10.0 - Request authority:https://login.windows.net/common resource:https://microsoft.sharepoint.com clientid:b26aadf8-566f-4478-926f-589f601d9c74 No result returned from acquireTokenSilent
                                                                                   com.microsoft.aad.adal.AuthenticationException: Refresh token is failed and prompt is not allowed
                                                                                       at com.microsoft.authorization.adal.ADALNetworkTasks$2.Log(ADALNetworkTasks.java:93)
                                                                                       at com.microsoft.aad.adal.Logger.logCommon(Logger.java:268)
                                                                                       at com.microsoft.aad.adal.Logger.error(Logger.java:242)
                                                                                       at com.microsoft.aad.adal.Logger.e(Logger.java:381)
                                                                                       at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:254)
                                                                                       at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:226)
                                                                                       at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:45)
                                                                                       at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:105)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)
09-20 15:58:26.890 26769-19525/com.microsoft.skydrive E/com.microsoft.authorization.OneDriveAuthenticator: refresh token AuthenticationException
                                                                                                           com.microsoft.aad.adal.AuthenticationException: Request authority:https://login.windows.net/common resource:https://microsoft.sharepoint.com clientid:b26aadf8-566f-4478-926f-589f601d9c74 No result returned from acquireTokenSilent
                                                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:257)
                                                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:226)
                                                                                                               at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:45)
                                                                                                               at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:105)
                                                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by weijjia** [comment]
@heidijinxujia already checked in the fix in the current playstore broker app.
