### ISSUE TITLE
Adal fails to recover in case the encryption certificate gets corrupted (AuthenticationContext throws IllegalStateException)

### ISSUE THREAD

**Issue by dbahat** [AzureAD/azure-activedirectory-library-for-android#713]
We're not sure how to repro it, but on some phones we saw the Adal encryption token somehow got corrupted, which resulted in the below stack trace:

caused by: java.lang.NullPointerException: chain == null
at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:1206)
at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:374)
at java.security.KeyStore.getEntry(KeyStore.java:645)
at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:539)
at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:426) 
at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:168) 
at com.microsoft.aad.adal.DefaultTokenCacheStore.<init>(DefaultTokenCacheStore.java:103) 
at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:152) 

In such a case, Adal does not attempt to reset the corrupted certificate, and each call to create AuthenticationContext results in java.lang.IllegalStateException: Failed to get private key from AndroidKeyStore (which is thrown from DefaultTokenCacheStore.<init>).
Using released Adal version 1.2.0.
We confirmed that if we manually deleting the corrupted certificate Adal generates a new one and creation of AuthenticationContext now works.

Inside StorageHelper.java we saw there is a call to resetKeyPairFromAndroidKeyStore() in case of exceptions during unwrap(), but this should also be done earlier in getSecretKeyFromAndroidKeyStore(), for example when calling KeyStore.getEntry().

**Comment by weijjia** [comment]
Can you check with the latest 1.10.0 and see if the issue persists? We have made some refactor work to improve key generation. Please re-open the issue if you see this again. Thanks.
