### ISSUE TITLE
Possible unhandled IllegalArgumentException inside DefaultTokenCacheStore

### ISSUE THREAD

**Issue by dbahat** [AzureAD/azure-activedirectory-library-for-android#721]
In case the encrypted (and encoded) token inside the DefaultTokenCacheStore somehow got corrupted, all calls to aquireToken() will trigger an unhandled IllegalArgumentException exception in a background thread, which the caller cannot catch.

Possible steps to repro:
1. Sign in with Adal using the DefaultTokenCacheStore and a rooted device (e.g. Android emulator)
2. Edit the generated Adal shared preferences file to have non-valid base64 chars
3. Try to call aquireToken() 
Result - Adal will crash the app from a background thread

Happens in released version 1.2.0.

Sample stack trace of such a crash:
java.lang.IllegalArgumentException: bad base-64
    at android.util.Base64.decode(Base64.java:161)
    at android.util.Base64.decode(Base64.java:136)
    at android.util.Base64.decode(Base64.java:118)
    at com.microsoft.aad.adal.StorageHelper.decrypt(StorageHelper.java:261)
    at com.microsoft.aad.adal.DefaultTokenCacheStore.decrypt(DefaultTokenCacheStore.java:140)
    at com.microsoft.aad.adal.DefaultTokenCacheStore.getItem(DefaultTokenCacheStore.java:158)
    at com.microsoft.aad.adal.TokenCacheAccessor.getRegularRefreshTokenCacheItem(TokenCacheAccessor.java:89)
    at com.microsoft.aad.adal.TokenCacheAccessor.getATFromCache(TokenCacheAccessor.java:62)
    at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(AcquireTokenSilentHandler.java:100)
    at com.microsoft.aad.adal.AuthenticationContext.localFlow(AuthenticationContext.java:1461)
    at com.microsoft.aad.adal.AuthenticationContext.acquireTokenAfterValidation(AuthenticationContext.java:1448)
    at com.microsoft.aad.adal.AuthenticationContext.acquireTokenLocalCall(AuthenticationContext.java:1261)
    at com.microsoft.aad.adal.AuthenticationContext.access$900(AuthenticationContext.java:73)
    at com.microsoft.aad.adal.AuthenticationContext$7.run(AuthenticationContext.java:1220)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)

**Comment by nazukj** [comment]
Rooted device scenarios are not supported. Thanks!
