### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'void com.microsoft.aad.adal.IWindowComponent.startActivityForResult(android.content.Intent, int)' on a null object reference

### ISSUE THREAD

**Issue by rpatton** [AzureAD/azure-activedirectory-library-for-android#727]
We are using 1.10.0 of the library and are seeing a few traces that look like below. Is this a known issue?

java.lang.NullPointerException: Attempt to invoke interface method 'void com.microsoft.aad.adal.IWindowComponent.startActivityForResult(android.content.Intent, int)' on a null object reference
           at com.microsoft.aad.adal.AcquireTokenWithBrokerRequest.acquireTokenWithBrokerInteractively(AcquireTokenWithBrokerRequest.java:93)
           at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenInteractiveFlow(AcquireTokenRequest.java:424)
           at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:233)
           at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:45)
           at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:105)
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
           at java.lang.Thread.run(Thread.java:818)

**Comment by weijjia** [comment]
In the acquireToken API call, you need to pass us either an activity or fragment. What do you pass in?

**Comment by rpatton** [comment]
We are calling the api below, which does not take an activity or fragment. It looks like from the ADAL source that this api calls the method with a null IWindowComponent which will lead to the crash. 

public void acquireToken(String resource, String clientId, String redirectUri,
            String loginHint, PromptBehavior prompt, String extraQueryParameters,
            AuthenticationCallback<AuthenticationResult> callback)

**Comment by weijjia** [comment]
Had an offline conversation, it seems that this is already resolved. Feel free to re-open the issue.
