### ISSUE TITLE
ProgressDialog in BasicWebViewClient in AuthenticationActivity leaks and can cause crashes

### ISSUE THREAD

**Issue by chilininsd** [AzureAD/azure-activedirectory-library-for-android#731]
Repro steps:
1.	Turn on the “Don’t Keep Activities” developer option
2.	Create one AuthenticationActivity through an interactive auth call
3.	Create a second AuthenticationActivity through an interactive call on top of the previous one
4.	Enter valid creds into the topmost activity

Expected:
I can finish the first activity after I notice that the second activity has already authenticated properly

Actual:
I attempt to finish the activity but crash with the following stack:

11-02 18:33:20.689 4711-4711/com.foo.myapp E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.IllegalArgumentException: View not attached to window manager
   at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:383)
   at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:285)
   at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
   at android.app.Dialog.dismissDialog(Dialog.java:323)
   at android.app.Dialog.dismiss(Dialog.java:306)
   **at com.microsoft.aad.adal.AuthenticationActivity.displaySpinner(AuthenticationActivity.java:740)
   at com.microsoft.aad.adal.AuthenticationActivity.access$1300(AuthenticationActivity.java:76)
   at com.microsoft.aad.adal.AuthenticationActivity$CustomWebViewClient.showSpinner(AuthenticationActivity.java:648)
   at com.microsoft.aad.adal.BasicWebViewClient.onPageFinished(BasicWebViewClient.java:141)**
   at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:323)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:5039)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
   at dalvik.system.NativeStart.main(Native Method).

What appears to be happening to me is that a race is occurring between when I attempt to finish the first AuthenticationActivity and when the BasicWebViewClient attempts to dismiss the overlaid ProgressDialog (Spinner). The spinner loses its host and then when Android attempts to dismiss it, the WindowManager proceeds to throw an IllegalArgumentException since it’s not a valid view anymore. It only seems to be reproing on an API17 and API19 emulators and only when “Don’t Keep Activities” is checked.

**Comment by hjymandroid** [comment]
I saw same thing when turn the "don't keep activities" on.

**Comment by nazukj** [comment]
All leaks were fixed. please reopen if still an issue.
