### ISSUE TITLE
BasicWebViewClient, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-It is failed to create device certificate response ver:1.2.0, additionalMessage CertAuthorities 

### ISSUE THREAD

**Issue by madhusudankapoor** [AzureAD/azure-activedirectory-library-for-android#735]
11-17 22:29:22.251 11560 ERROR [ADAL] AdalUtils: tag: BasicWebViewClient, message: 2016-11-17 22:29:22-34a2ba55-a387-4c84-970f-824e1f0d4c42-It is failed to create device certificate response ver:1.2.0, additionalMessage CertAuthorities com.microsoft.aad.adal.AuthenticationException: CertAuthorities
                at com.microsoft.aad.adal.ChallengeResponseBuilder.validateChallengeRequest(ChallengeResponseBuilder.java:286)
                at com.microsoft.aad.adal.ChallengeResponseBuilder.getChallengeRequest(ChallengeResponseBuilder.java:299)
                at com.microsoft.aad.adal.ChallengeResponseBuilder.getChallengeResponseFromUri(ChallengeResponseBuilder.java:95)
                at com.microsoft.aad.adal.BasicWebViewClient$3.run(BasicWebViewClient.java:173)
                at java.lang.Thread.run(Thread.java:761)
, adalError: It is failed to create device certificate response

**Comment by madhusudankapoor** [comment]
ADAL WebView is failing during sign with above error

**Comment by weijjia** [comment]
What is the scenario, is it on prem case? If it's on prem, we have identified an issue with adal, and fix is going to be shipped in 1.11.0.
