### ISSUE TITLE
Crash with exception - Failed to load generated key pair from keystore 

### ISSUE THREAD

**Issue by rama-juluri** [AzureAD/azure-activedirectory-library-for-android#740]
We are seeing the following exception in our app causing the app to crash during sign-in. Is it a known issue? Is there a workaround ? 

This crash is happening across all Android versions and device models, however the number of crashes are very high on OnePlus & Xiaomi devices with Android 7.1.

```
### java.security.ProviderException: Failed to load generated key pair from keystore
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:518)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:470)
	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:699)
	at com.microsoft.aad.adal.StorageHelper.generateKeyPairFromAndroidKeyStore(StorageHelper.java:414)
	at com.microsoft.aad.adal.StorageHelper.getKeyOrCreate(StorageHelper.java:362)
	at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForEncryption(StorageHelper.java:320)
	at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:178)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:122)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:190)
	at com.microsoft.aad.adal.TokenCacheAccessor.setItemToCacheForUser(TokenCacheAccessor.java:227)
	at com.microsoft.aad.adal.TokenCacheAccessor.updateTokenCache(TokenCacheAccessor.java:165)
	at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:121)
	at com.microsoft.aad.adal.AcquireTokenRequest$4.run(AcquireTokenRequest.java:651)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:230)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:259)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:509)
	... 15 more
Caused by: android.security.KeyStoreException: -22
	at android.security.KeyStore.getKeyStoreException(KeyStore.java:666)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:231)
```

**Comment by khalidaw** [comment]
We had also this error, but it was fixed for us in 1.10

**Comment by weijjia** [comment]
Please check in this link https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore. 

We did so something to catch some runtime exception to prevent the app from crashing, but it won't help with signin. User will still need to sign-in again and again, since nothing is saved in the cache.

**Comment by hram** [comment]
@khalidaw can you please get link to commit with fixes?
I have the same error and cant fix it

**Comment by caltseng** [comment]
@weijjia , the link you provide doesn't actually contain the above exception and what is happening there

**Comment by saeidz70** [comment]
We updated MSAL to 2.2.1 Version, but we got the same error.

[https://github.com/AzureAD/microsoft-authentication-library-for-android/issues/1489]
