### ISSUE TITLE
java.lang.NullPointerException in 1.10.0

### ISSUE THREAD

**Issue by imakhalova** [AzureAD/azure-activedirectory-library-for-android#746]
accessTokenItem can be null in method getStaleToken. Add null check
stack trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.microsoft.aad.adal.TokenCacheItem.getAccessToken()' on a null object reference
	at com.microsoft.aad.adal.TokenCacheAccessor.getStaleToken(TokenCacheAccessor.java:115)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.acquireTokenWithRefreshToken(AcquireTokenSilentHandler.java:133)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.acquireTokenWithCachedItem(AcquireTokenSilentHandler.java:293)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryFRT(AcquireTokenSilentHandler.java:258)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryMRRT(AcquireTokenSilentHandler.java:217)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.tryRT(AcquireTokenSilentHandler.java:177)
	at com.microsoft.aad.adal.AcquireTokenSilentHandler.getAccessToken(AcquireTokenSilentHandler.java:104)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilentLocally(AcquireTokenRequest.java:319)
	at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenSilentFlow(AcquireTokenRequest.java:287)
	at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:242)
	at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:226)
	at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:45)
	at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:105)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by heidijinxujia** [comment]
Thank you very much for reporting the issue. The fix is under review in PR #775

**Comment by weijjia** [comment]
@heidijinxujia already fixed the issue in the upcoming release 1.12.0.
