### ISSUE TITLE
getSecretKeyFromAndroidKeyStore InvalidKeyException exception

### ISSUE THREAD

**Issue by hjymandroid** [AzureAD/azure-activedirectory-library-for-android#760]
Class:StorageHelper message:2017-01-23 05:54:52-null-Failed to get private key from AndroidKeyStore ver:1.2.0 additionalMessage: java.security.InvalidKeyException: javax.crypto.BadPaddingException: error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02
	at com.android.org.conscrypt.OpenSSLCipherRSA.engineUnwrap(OpenSSLCipherRSA.java:340)
	at javax.crypto.Cipher.unwrap(Cipher.java:1409)
	at com.microsoft.aad.adal.StorageHelper.unwrap(StorageHelper.java:585)
	at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:450)
	at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:168)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.<init>(DefaultTokenCacheStore.java:103)
	at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:152)
	
See a ton of this in v1.2.0. Not sure whether this got fixed in latest version.

**Comment by weijjia** [comment]
Please check this link https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
