### ISSUE TITLE
StorageHelper.getKeyPairFromAndroidKeyStore UnrecoverableKeyException

### ISSUE THREAD

**Issue by hjymandroid** [AzureAD/azure-activedirectory-library-for-android#761]
Class:StorageHelper message:2017-03-01 17:10:04-null-Failed to get private key from AndroidKeyStore ver:1.2.0 additionalMessage: java.security.UnrecoverableKeyException: Failed to obtain information about private key
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:216)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:252)
	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePrivateKeyFromKeystore(AndroidKeyStoreProvider.java:263)
	at android.security.keystore.AndroidKeyStoreSpi.engineGetKey(AndroidKeyStoreSpi.java:93)
	at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:372)
	at java.security.KeyStore.getEntry(KeyStore.java:645)
	at com.microsoft.aad.adal.StorageHelper.getKeyPairFromAndroidKeyStore(StorageHelper.java:539)
	at com.microsoft.aad.adal.StorageHelper.getSecretKeyFromAndroidKeyStore(StorageHelper.java:426)
	at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForAPI(StorageHelper.java:168)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.<init>(DefaultTokenCacheStore.java:103)
	at com.microsoft.aad.adal.AuthenticationContext.<init>(AuthenticationContext.java:152)

**Comment by weijjia** [comment]
Please check this link https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
