### ISSUE TITLE
AcquireTokenRequest with ON_ACTIVITY_RESULT_INTENT_NULL error

### ISSUE THREAD

**Issue by hjymandroid** [AzureAD/azure-activedirectory-library-for-android#765]
It happens to adal 1.10 and 1.2.0 also. It effected a lot users of us. So please fix it!

To reproduce, just turn on "Don't keep activities in background" setting in dev mode. And then try to login user with ADAL. It happens a lot to our customers, when it happens the caller onError is never triggered since waitingRequestOnError never has a chance to be fired. As a result, the user sign in request is hanging over there, which is a very bad experience.

Stacktrace:

02-03 15:00:56.509 2774-2774/? E/AcquireTokenRequest: ON_ACTIVITY_RESULT_INTENT_NULL:2017-02-03 23:00:56-5b613b63-6d6f-4114-b97b-13abc6e-onActivityResult did not find waiting request for RequestId:71031960 ver:1.10.0 
02-03 15:00:56.629 2774-4177/? E/AcquireTokenRequest: AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED:2017-02-03 23:00:56-ee28979e-6aae-4131-80e2-424710c-Prompt is not allowed and failed to get token: ver:1.11.0 Request authority:https://login.microsoftonline.com/common resource:https://msmamservice.api.application clientid:d3590ed6-52b3-4102-aeff-aad2292 No result returned from acquireTokenSilent
02-03 15:00:56.629 2774-4177/? E/adal: 2017-02-03 23:00:56-ee28979e-6aae-4131-80e2-424710c2Prompt is not allowed and failed to get token: ver:1.11.0 (additional: "Request authority:https://login.microsoftonline.com/common resource:https://msmamservice.api.application clientid:d3590ed6-52b3-4102-aeff-aad2292 No result returned from acquireTokenSilent"), error: AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED - "Refresh token is failed and prompt is not allowed"
02-03 15:00:56.759 3142-3247/? E/[IMS6.0]: ImsEventLoop: select (1)
02-03 15:00:56.759 3142-3286/? E/[IMS6.0]: IMS_onResponse() Resp Id:600
02-03 15:00:56.789 2774-5808/? E/AMServiceAuthentication: Failed to acquire MAMService token;  Correlation ID = ee28979e-6aae-4131-80e2-424710c2eb
  com.microsoft.aad.adal.AuthenticationException: Request authority:https://login.microsoftonline.com/common resource:https://msmamservice.api.application clientid:d3590ed6-52b3-4102-aeff-aad2292a No result returned from acquireTokenSilent
      at com.microsoft.aad.adal.AcquireTokenRequest.tryAcquireTokenSilent(AcquireTokenRequest.java:256)
      at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:224)
      at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:44)
      at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:103)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
      at java.lang.Thread.run(Thread.java:818)
02-03 15:00:57.239 5836-5836/? E/Zygote: v2
02-03 15:00:57.249 5836-5836/? E/Zygote: accessInfo : 0
02-03 15:00:57.319 3085-3085/? E/lowmemorykiller: Error writing /proc/5836/oom_score_adj; errno=22
02-03 15:00:57.399 2774-2774/? E/WindowManager: android.view.WindowLeaked: Activity com.microsoft.aad.adal.AuthenticationActivity has leaked window android.widget.PopupWindow$PopupDecorView{869de8e V.E...... ........ 0,0-80,96} that was originally added here
    at android.view.ViewRootImpl.<init>(ViewRootImpl.java:565)
    at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:326)
    at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:91)
    at android.widget.PopupWindow.invokePopup(PopupWindow.java:1329)
    at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1077)
    at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1035)
    at org.chromium.android_webview.PopupTouchHandleDrawable.show(PopupTouchHandleDrawable.java:508)
    at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
    at org.chromium.android_webview.AwContents.access$4700(AwContents.java:99)
    at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:2992)
    at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:32327)
    at android.webkit.WebView.onDraw(WebView.java:2516)
    at android.view.View.draw(View.java:17469)
    at android.view.View.updateDisplayListIfDirty(View.java:16464)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
    at android.view.View.updateDisplayListIfDirty(View.java:16424)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
    at android.view.View.updateDisplayListIfDirty(View.java:16424)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
    at android.view.View.updateDisplayListIfDirty(View.java:16424)
    at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3905)
    at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3885)
    at android.view.View.updateDisplayListIfDirty(View.java:16424)
    at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:325)
    at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:331)
    at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:366)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:3134)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2933)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
    at android.view.Choreographer.doCallbacks(Choreographer.java:695)
    at android.view.Choreographer.doFrame(Choreographer.java:631)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by hjymandroid** [comment]
A little more debugging found out when AcquireTokenRequest onActivityResult is called which includes the following code
try {
                    waitingRequest = mAuthContext.getWaitingRequest(requestId);
                    Logger.v(TAG, "onActivityResult RequestId:" + requestId);
                } catch (final AuthenticationException authenticationException) {
                    Logger.e(TAG, "onActivityResult did not find waiting request for RequestId:"
                            + requestId, "", ADALError.ON_ACTIVITY_RESULT_INTENT_NULL);
                    return;
                }
the pending request is not properly saved when AuthenticationContext is reclaimed by OS. 
The mAuthContext getWaitingRequest is throwing exceptions since mAuthContext is a different instance with empty mDelegateMap.

**Comment by weijjia** [comment]
@hjymandroid This should only be a bug we introduced in 1.10, did you also see it in 1.2.0? if so, can you please share logs?

**Comment by hjymandroid** [comment]
@weijjia  Yes, but i don't have the detailed stacktrace, but the following log we got in our logging system:
Class:AuthenticationContext message:2017-02-16 15:35:24-null-onActivityResult did not find waiting request for RequestId:57309394 ver:1.2.0 additionalMessage: level:Error errorCode:ON_ACTIVITY_RESULT_INTENT_NULL"

Also it might be the same error code is generated, but things are different.

**Comment by nycodes9** [comment]
This is also happening on 1.2.2 same reason as above

**Comment by addev-ashish** [comment]
The fix shipped with 1.12.0
