### ISSUE TITLE
Crash in AcquireTokenInteractiveRequest.startAuthenticationActivity

### ISSUE THREAD

**Issue by hjymandroid** [AzureAD/azure-activedirectory-library-for-android#766]
java.lang.IllegalStateException: Fragment LoginFragment{727f11b} not attached to Activity
         at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:949)
         at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:940)
         at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.startAuthenticationActivity(AcquireTokenInteractiveRequest.java:144)
         at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireToken(AcquireTokenInteractiveRequest.java:77)
         at com.microsoft.aad.adal.AcquireTokenRequest.acquireTokenInteractiveFlow(AcquireTokenRequest.java:430)
         at com.microsoft.aad.adal.AcquireTokenRequest.performAcquireTokenRequest(AcquireTokenRequest.java:233)
         at com.microsoft.aad.adal.AcquireTokenRequest.access$200(AcquireTokenRequest.java:45)
         at com.microsoft.aad.adal.AcquireTokenRequest$1.run(AcquireTokenRequest.java:105)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
         at java.lang.Thread.run(Thread.java:818)

reproduce: 
when the login starts, rotate the screen.

**Comment by weijjia** [comment]
Do you have the following config in your manifest?
android:configChanges="orientation"

**Comment by hjymandroid** [comment]
Yes we do:

<activity
            android:name="com.microsoft.aad.adal.AuthenticationActivity"
            android:label="@string/adal_login_title"
            android:configChanges="orientation|keyboardHidden|screenSize" />

**Comment by hjymandroid** [comment]
<activity
            android:name="com.microsoft.aad.adal.AuthenticationActivity"
            android:label="@string/adal_login_title"
            android:configChanges="orientation|keyboardHidden|screenSize" />

**Comment by weijjia** [comment]
One follow-up question, for the acquireToken api call, do you pass in Fragment?

**Comment by hjymandroid** [comment]
Yes, we do.

Thanks.

Hongjie

**Comment by nazukj** [comment]
Closing issue. if it repro-es please re-open.

**Comment by kungfucop** [comment]
This was never solved, why we close it?

**Comment by nazukj** [comment]
This was no repro on our end with no updates since April. Hence, it was closed. If you have an active repro, please provide logs and re-open the issue.

Thanks!
