### ISSUE TITLE
Unbind service causing IllegalArgumentException: Service not registered

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#803]
java.lang.IllegalArgumentException: Service not registered: com.microsoft.aad.adal.BrokerAccountServiceHandler$BrokerAccountServiceConnection@a9e6601
                at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1345)
                at android.app.ContextImpl.unbindService(ContextImpl.java:1536)
                at android.content.ContextWrapper.unbindService(ContextWrapper.java:700)
                at com.microsoft.aad.adal.BrokerAccountServiceHandler$BrokerAccountServiceConnection$1.run(BrokerAccountServiceHandler.java:356)
                at android.os.Handler.handleCallback(Handler.java:751)
                at android.os.Handler.dispatchMessage(Handler.java:95)
                at android.os.Looper.loop(Looper.java:154)
                at android.app.ActivityThread.main(ActivityThread.java:6688)
                at java.lang.reflect.Method.invoke(Native Method)
                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by addev-ashish** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/804
