### ISSUE TITLE
Investigate why unbindService is throwing IllegalArgumentException

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#808]
```java
java.lang.IllegalArgumentException: Service not registered: com.microsoft.aad.adal.BrokerAccountServiceHandler$BrokerAccountServiceConnection@a9e6601
at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1345)
at android.app.ContextImpl.unbindService(ContextImpl.java:1536)
at android.content.ContextWrapper.unbindService(ContextWrapper.java:700)
at com.microsoft.aad.adal.BrokerAccountServiceHandler$BrokerAccountServiceConnection$1.run(BrokerAccountServiceHandler.java:356)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6688)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by weijjia** [comment]
The IllegalArgumentException is thrown if the service that you're trying to unbind is not even registered http://androidxref.com/7.0.0_r1/xref/frameworks/base/core/java/android/app/LoadedApk.java#1289. 

ADAL uses a safe way to handle the service binding and unbinding, we have an callback when service is connected, and unBindService is only called when background service call succeeds and mBound is true. If for some reason, OS kills the service which will cause service disconnect, it won't be called. 

Unbind call is also a thread safe call, unbind request are all posted back to the main message queue and mBound will be set to false. Even though the unbind is called multiple times for the same service connection, it will be unBind once. 

Given all the above facts, we suspect this is an issue in the OS itself. Since no actions on our side for now, we'll close the issue. Feel free to reopen.
