### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "ag`d`d`bche`GMT+00:00" (at offset 0)

### ISSUE THREAD

**Issue by jaredsburrows** [AzureAD/azure-activedirectory-library-for-android#812]
## Phone model:
SAMSUNG SM-G925I

## Android version:
6.0.1

## Stacktrace:
```
java.security.ProviderException: Failed to generate self-signed certificate
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:504)
	at java.security.KeyPairGenerator$KeyPairGeneratorImpl.generateKeyPair(KeyPairGenerator.java:276)
	at com.microsoft.aad.adal.StorageHelper.generateKeyPairFromAndroidKeyStore(StorageHelper.java:414)
	at com.microsoft.aad.adal.StorageHelper.getKeyOrCreate(StorageHelper.java:362)
	at com.microsoft.aad.adal.StorageHelper.loadSecretKeyForEncryption(StorageHelper.java:320)
	at com.microsoft.aad.adal.StorageHelper.encrypt(StorageHelper.java:178)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.encrypt(DefaultTokenCacheStore.java:122)
	at com.microsoft.aad.adal.DefaultTokenCacheStore.setItem(DefaultTokenCacheStore.java:190)
	at com.microsoft.aad.adal.TokenCacheAccessor.setItemToCacheForUser(TokenCacheAccessor.java:227)
	at com.microsoft.aad.adal.TokenCacheAccessor.updateTokenCache(TokenCacheAccessor.java:165)
	at com.microsoft.aad.adal.AcquireTokenInteractiveRequest.acquireTokenWithAuthCode(AcquireTokenInteractiveRequest.java:121)
	at com.microsoft.aad.adal.AcquireTokenRequest$4.run(AcquireTokenRequest.java:651)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.IllegalArgumentException: invalid date string: Unparseable date: "ag`d`d`bche`GMT+00:00" (at offset 0)
	at com.android.org.bouncycastle.asn1.ASN1UTCTime.<init>(ASN1UTCTime.java:115)
	at com.android.org.bouncycastle.asn1.DERUTCTime.<init>(DERUTCTime.java:23)
	at com.android.org.bouncycastle.asn1.x509.Time.<init>(Time.java:67)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificateWithFakeSignature(AndroidKeyStoreKeyPairGeneratorSpi.java:618)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateSelfSignedCertificate(AndroidKeyStoreKeyPairGeneratorSpi.java:565)
	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:502)
	... 14 more
```

**Comment by nazukj** [comment]
This is a known issue with Android KeyStore. Please see wiki linked below for mitigation steps. 
https://github.com/AzureAD/azure-activedirectory-library-for-android/wiki/Common-Issues-With-AndroidKeyStore
Feel free to reopen if this does not resolve your issue. Thanks!

**Comment by jaredsburrows** [comment]
Thanks @nazukj!
