### ISSUE TITLE
Crash in applicationReceiver when empty string is passed to canSwitchToBroker

### ISSUE THREAD

**Issue by addev-ashish** [AzureAD/azure-activedirectory-library-for-android#813]
04-07 13:12:10.734 6144-6144/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.microsoft.skydrive, PID: 6144
                                                 java.lang.RuntimeException: Unable to start receiver com.microsoft.aad.adal.ApplicationReceiver: java.lang.IllegalArgumentException: DEVELOPER_AUTHORITY_IS_NOT_VALID_URL
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2732)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.IllegalArgumentException: DEVELOPER_AUTHORITY_IS_NOT_VALID_URL
                                                     at com.microsoft.aad.adal.BrokerProxy.canSwitchToBroker(BrokerProxy.java:130)
                                                     at com.microsoft.aad.adal.ApplicationReceiver.onReceive(ApplicationReceiver.java:112)
                                                     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2725)
                                                     at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1421) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:148) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by addev-ashish** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-android/pull/814
