### ISSUE TITLE
android.view.InflateException on AuthenticationActivity after upgrade to API 25

### ISSUE THREAD

**Issue by LesterTheTester** [AzureAD/azure-activedirectory-library-for-android#818]
Hi, we have a very similar issue to https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/771. We only started seeing this exception in our production app once we raised our targetSdkVersion to 25 and our build tools to 25.0.2.

Package: com.yammer.v1
Version Code: 1341
Version Name: 5.4.14.1341
Android: 7.0
Android Build: NRD90M release-keys
Manufacturer: HTC
Model: HTC One M9
Thread: main-1
CrashReporter Key: 29099BE0-04F6-CEA5-77F3-A638DA1289AE189E8E87
Start Date: Wed Apr 12 11:44:52 EDT 2017
Date: Wed Apr 12 11:45:28 EDT 2017

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.yammer.v1/com.microsoft.aad.adal.AuthenticationActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.webkit.WebView
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2729)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2790)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:173)
at android.app.ActivityThread.main(ActivityThread.java:6523)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class android.webkit.WebView
Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.webkit.WebView
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Constructor.newInstance0(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
at android.view.LayoutInflater.createView(LayoutInflater.java:645)
at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
at android.view.LayoutInflater.onCreateView(LayoutInflater.java:717)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:785)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
at android.transition.Scene.enter(Scene.java:175)
at com.android.internal.policy.PhoneWindow.transitionTo(PhoneWindow.java:500)
at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:431)
at android.app.Activity.setContentView(Activity.java:2423)
at com.microsoft.aad.adal.AuthenticationActivity.onCreate(AuthenticationActivity.java:152)
at android.app.Activity.performCreate(Activity.java:6673)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2790)
at android.app.ActivityThread.-wrap12(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:173)
at android.app.ActivityThread.main(ActivityThread.java:6523)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
Caused by: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 298713250 actual: 288309150
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:371)
at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:194)
at android.webkit.WebView.getFactory(WebView.java:2324)
at android.webkit.WebView.ensureProviderCreated(WebView.java:2319)
at android.webkit.WebView.setOverScrollMode(WebView.java:2378)
at android.view.View.(View.java:4014)
at android.view.View.(View.java:4131)
at android.view.ViewGroup.(ViewGroup.java:578)
at android.widget.AbsoluteLayout.(AbsoluteLayout.java:55)
at android.webkit.WebView.(WebView.java:626)
at android.webkit.WebView.(WebView.java:571)
at android.webkit.WebView.(WebView.java:554)
at android.webkit.WebView.(WebView.java:541)
... 29 more
Caused by: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to verify WebView provider, version code is lower than expected: 298713250 actual: 288309150
at android.webkit.WebViewFactory.verifyPackageInfo(WebViewFactory.java:243)
at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:303)
at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:330)
... 41 more

**Comment by addev-ashish** [comment]
Most likely a rooted device with a weird webview setup.
