### ISSUE TITLE
DNS Assistance Causes Unit Test Failure

### ISSUE THREAD

**Issue by iambmelt** [AzureAD/azure-activedirectory-library-for-android#853]
Some ISPs provide [DNS Assistance ](https://www.verizon.com/support/consumer/internet/opt-out-of-dns-assist)when hostname lookups fail. In the case of an ISP or network DNS providing such assistance, [`WebRequestHandlerTest#testNonExistentUrl()` ](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/dev/adal/src/androidTest/java/com/microsoft/aad/adal/WebRequestHandlerTests.java#L179-L190)can fail (by actually resolving to _something_) because of DNS-side redirection. While this may not be an issue for CI - some users/contributors may see this test fail on their network.

```java
junit.framework.AssertionFailedError: Unreachable host, should throw IOException
at junit.framework.Assert.fail(Assert.java:50)
at com.microsoft.aad.adal.WebRequestHandlerTests.testNonExistentUrl(WebRequestHandlerTests.java:185)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1932)
```

**Comment by iambmelt** [comment]
Closing, noop
